//! Key metadata: which table columns are part of a primary key, a foreign
//! key or a unique key, so the UI can mark them in result headers, the explorer's column nodes
//! and the inspector, and name the source table of a result (the SQL INSERT copy).
//!
//! A driver with `Capabilities::key_metadata` builds one [`KeyCatalog`] per connection on its
//! metadata session and names the origin of every result column ([`ColumnOrigin`]); the UI
//! keeps the catalog per profile and looks columns up when it draws, so a warm cache costs no
//! round trip per query. A result column without an origin (an expression, a function) has no
//! marks. Every column of a composite key is marked.

use super::ColumnOrigin;
use crate::sql::dialect::Dialect;
use crate::sql::lexer::{Tok, Token, lex};
use std::collections::{BTreeMap, HashMap, HashSet};

/// The keys a column is part of.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct KeyMarks {
    /// Part of the primary key.
    pub pk: bool,
    /// Part of a foreign key (it references another table).
    pub fk: bool,
    /// Part of a unique key other than the primary key.
    pub unique: bool,
}

impl KeyMarks {
    pub fn any(self) -> bool {
        self.pk || self.fk || self.unique
    }
}

/// One kind of key.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum KeyKind {
    Primary,
    Foreign,
    Unique,
}

/// How the database fills a column on `INSERT` (PostgreSQL `attgenerated` / `attidentity`).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Generated {
    /// An ordinary column (also `GENERATED BY DEFAULT AS IDENTITY`: a value may be given).
    #[default]
    No,
    /// `GENERATED ALWAYS AS (…) STORED` (or `VIRTUAL`): no value may be given, only `DEFAULT`.
    Expression,
    /// `GENERATED ALWAYS AS IDENTITY`: a value is taken only with `OVERRIDING SYSTEM VALUE`.
    IdentityAlways,
}

/// A column of a table: its name, its keys and how it is generated.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ColumnKeys {
    pub name: String,
    pub marks: KeyMarks,
    pub generated: Generated,
}

/// A table (or view): its schema, name and columns by number.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TableKeys {
    pub schema: String,
    pub name: String,
    pub columns: BTreeMap<i16, ColumnKeys>,
    /// A view (or materialized view), not a table.
    pub view: bool,
}

/// The tables of a database with their columns and keys.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct KeyCatalog {
    tables: BTreeMap<u32, TableKeys>,
    /// `(schema, table)` → table id, for lookups by name (the explorer's column nodes).
    by_name: HashMap<(String, String), u32>,
}

impl KeyCatalog {
    /// Add table `id` with its columns (number, name); no keys yet.
    pub fn add_table(&mut self, id: u32, schema: &str, name: &str, columns: impl IntoIterator<Item = (i16, String)>) {
        let columns = columns
            .into_iter()
            .map(|(n, name)| (n, ColumnKeys { name, marks: KeyMarks::default(), generated: Generated::No }))
            .collect();
        self.by_name.insert((schema.to_string(), name.to_string()), id);
        self.tables.insert(id, TableKeys { schema: schema.to_string(), name: name.to_string(), columns, view: false });
    }

    /// Table `id` is a view (or a materialized view).
    pub fn set_view(&mut self, id: u32) {
        if let Some(t) = self.tables.get_mut(&id) {
            t.view = true;
        }
    }

    /// Mark the columns `columns` of table `id` as part of a key of kind `kind` (each member
    /// of a composite key). Unknown tables and columns are skipped.
    pub fn mark(&mut self, id: u32, columns: &[i16], kind: KeyKind) {
        let Some(t) = self.tables.get_mut(&id) else { return };
        for n in columns {
            if let Some(c) = t.columns.get_mut(n) {
                match kind {
                    KeyKind::Primary => c.marks.pk = true,
                    KeyKind::Foreign => c.marks.fk = true,
                    KeyKind::Unique => c.marks.unique = true,
                }
            }
        }
    }

    /// Column `column` of table `id` is generated as `g` (unknown tables and columns are
    /// skipped).
    pub fn set_generated(&mut self, id: u32, column: i16, g: Generated) {
        if let Some(c) = self.tables.get_mut(&id).and_then(|t| t.columns.get_mut(&column)) {
            c.generated = g;
        }
    }

    /// The keys of the column a result column comes from (none without an origin).
    pub fn marks(&self, origin: Option<&ColumnOrigin>) -> KeyMarks {
        origin.and_then(|o| self.column(o)).map(|c| c.marks).unwrap_or_default()
    }

    /// The table column `o` names, if the catalog knows it.
    pub fn column(&self, o: &ColumnOrigin) -> Option<&ColumnKeys> {
        let (table, column) = self.locate(o)?;
        self.tables.get(&table)?.columns.get(&column)
    }

    /// The table id and column number of `o`: as they are for a [`ColumnOrigin::Pg`] (known
    /// to the catalog or not), looked up by name for a [`ColumnOrigin::Named`].
    fn locate(&self, o: &ColumnOrigin) -> Option<(u32, i16)> {
        match o {
            ColumnOrigin::Pg { table, column } => Some((*table, *column)),
            ColumnOrigin::Named { schema, table, column } => {
                let id = *self.by_name.get(&(schema.clone(), table.clone()))?;
                let (n, _) = self.tables.get(&id)?.columns.iter().find(|(_, c)| c.name == *column)?;
                Some((id, *n))
            }
        }
    }

    /// Table `id`.
    pub fn table(&self, id: u32) -> Option<&TableKeys> {
        self.tables.get(&id)
    }

    /// The keys of column `column` of `schema.table` (none when it is not known).
    pub fn marks_by_name(&self, schema: &str, table: &str, column: &str) -> KeyMarks {
        self.by_name
            .get(&(schema.to_string(), table.to_string()))
            .and_then(|id| self.tables.get(id))
            .and_then(|t| t.columns.values().find(|c| c.name == column))
            .map(|c| c.marks)
            .unwrap_or_default()
    }

    /// Table `name` of `schema`, or without a schema the one table of that name in any schema.
    pub fn find(&self, schema: Option<&str>, name: &str) -> Result<&TableKeys, NotInsertable> {
        if let Some(schema) = schema {
            let id = self.by_name.get(&(schema.to_string(), name.to_string()));
            return id.and_then(|id| self.tables.get(id)).ok_or(NotInsertable::NoSuchTable);
        }
        let mut hits = self.tables.values().filter(|t| t.name == name);
        match (hits.next(), hits.next()) {
            (Some(t), None) => Ok(t),
            (None, _) => Err(NotInsertable::NoSuchTable),
            (Some(_), Some(_)) => Err(NotInsertable::AmbiguousTable),
        }
    }

    /// How many tables it knows.
    pub fn len(&self) -> usize {
        self.tables.len()
    }

    pub fn is_empty(&self) -> bool {
        self.tables.is_empty()
    }
}

/// Why rows are not copied as `INSERT` statements.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NotInsertable {
    /// Not one `SELECT` (`VALUES`, `TABLE`, `SHOW`, `SELECT … INTO`, a parenthesized query).
    NotSelect,
    /// A `WITH` query: its names hide what they read.
    With,
    /// More than one table in `FROM` (a join, a comma), or columns from several tables.
    SeveralTables,
    /// A subquery in the select list or in `FROM`.
    Subquery,
    /// `UNION`, `INTERSECT` or `EXCEPT`.
    SetOperation,
    /// `GROUP BY`, `HAVING` or `DISTINCT ON`: a row may stand for several rows of the table.
    Grouping,
    /// A window function (`OVER`, `WINDOW`).
    Window,
    /// `FROM` names no plain table (a function, `LATERAL`, `ROWS FROM`, `TABLESAMPLE`), or
    /// there is no `FROM`.
    NotATable,
    /// A column is computed (an expression, an aggregate), not a column of the table.
    Computed,
    /// The columns come from another table than the one `FROM` names.
    OtherTable,
    /// One table column is selected twice: the column list would name it twice.
    RepeatedColumn,
    /// The rows come from a view.
    View,
    /// The tables' columns are not known: the key cache is not read yet, or could not be.
    NoCatalog,
    /// The table is not in the key cache (created or changed outside the app).
    UnknownTable,
    /// Two columns have the same name: the column list would name one column twice.
    DuplicateNames,
    /// Every column is generated by the database (`GENERATED ALWAYS AS (…)`): there is no value
    /// to insert.
    OnlyGenerated,
    /// `:copy insert`: there is no table of that name.
    NoSuchTable,
    /// `:copy insert`: tables of that name are in several schemas.
    AmbiguousTable,
    /// `:copy insert`: the table has no column of this result column's name.
    NoSuchColumn(String),
    /// `:copy insert`: this column of the table is generated (`GENERATED ALWAYS AS (…)`).
    GeneratedColumn(String),
}

/// The `INSERT` statements to write: the table and which result columns go into which of its
/// columns.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InsertPlan<'a> {
    pub table: &'a TableKeys,
    /// The result columns to write (their index in the result, their name in the table), in
    /// result order: every column except the generated ones.
    pub columns: Vec<(usize, &'a str)>,
    /// The generated columns left out (their names in the table).
    pub skipped: Vec<&'a str>,
    /// A `GENERATED ALWAYS AS IDENTITY` column is written: the statements need
    /// `OVERRIDING SYSTEM VALUE`.
    pub overriding: bool,
}

/// The table rows of a result are copied into, when the copy is automatic: the result must
/// provably be a projection of rows of exactly one table instance, else it is refused (an
/// allowlist: when in doubt, refuse).
///
/// `sql` (the statement that produced the result, lexed) must be one `SELECT` with exactly one
/// plain table in `FROM` ([`single_table`]: no join, comma, `WITH`, subquery in the select list
/// or `FROM`, set operation, `LATERAL`, table function, `GROUP BY`, `HAVING`, `DISTINCT ON`
/// or window function). The explorer's own `SELECT * FROM schema.table` is such a statement.
/// Every result column (`origins`, from the RowDescription) must be a column of that table,
/// each column once, and the result names `names` must be distinct. A view is refused.
///
/// Generated columns follow PostgreSQL's rules for `INSERT`: a `GENERATED ALWAYS AS (…)`
/// column takes no value (only `DEFAULT`), so it is left out and the server computes it again
/// from the other columns; a `GENERATED ALWAYS AS IDENTITY` column keeps its value, written
/// with `OVERRIDING SYSTEM VALUE` (as `pg_dump --inserts` does), so the copied rows keep their
/// ids. A result of generated columns only is refused.
pub fn insert_source<'a>(
    d: Dialect,
    catalog: Option<&'a KeyCatalog>,
    origins: &[Option<ColumnOrigin>],
    names: &[&str],
    sql: &str,
) -> Result<InsertPlan<'a>, NotInsertable> {
    use NotInsertable::*;
    let from = single_table(d, sql)?;
    let origins: Vec<&ColumnOrigin> = origins.iter().map(Option::as_ref).collect::<Option<_>>().ok_or(Computed)?;
    let origins: Vec<Located> = origins.into_iter().map(|o| locate(catalog, o)).collect::<Result<_, _>>()?;
    let first = origins.first().ok_or(Computed)?;
    if origins.iter().any(|o| o.table != first.table) {
        return Err(SeveralTables);
    }
    let mut seen = HashSet::new();
    if !origins.iter().all(|o| seen.insert(o.column)) {
        return Err(RepeatedColumn);
    }
    let table = catalog.ok_or(NoCatalog)?.table(first.table).ok_or(UnknownTable)?;
    if !from.names(table) {
        return Err(OtherTable);
    }
    if table.view {
        return Err(View);
    }
    let columns =
        origins.iter().map(|o| table.columns.get(&o.column)).collect::<Option<Vec<_>>>().ok_or(UnknownTable)?;
    distinct(names)?;
    plan(table, columns)
}

/// A result column's table id and column number in the catalog.
struct Located {
    table: u32,
    column: i16,
}

/// Where origin `o` is in `catalog`. A [`ColumnOrigin::Pg`] names it by number (whether the
/// catalog knows it is checked later); a [`ColumnOrigin::Named`] needs the catalog to find it.
fn locate(catalog: Option<&KeyCatalog>, o: &ColumnOrigin) -> Result<Located, NotInsertable> {
    let (table, column) = match o {
        ColumnOrigin::Pg { table, column } => (*table, *column),
        ColumnOrigin::Named { .. } => {
            catalog.ok_or(NotInsertable::NoCatalog)?.locate(o).ok_or(NotInsertable::UnknownTable)?
        }
    };
    Ok(Located { table, column })
}

/// Why rows are not copied as `UPDATE` statements.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum NotUpdatable {
    /// Not rows of one table (the `INSERT` allowlist, [`insert_source`], refused them).
    NotInsertable(NotInsertable),
    /// The table has no primary key: nothing names one row.
    NoPrimaryKey,
    /// These primary key columns are not in the result.
    MissingKey(Vec<String>),
    /// Every column of the result is part of the key or generated: nothing to set.
    NothingToSet,
}

/// The `UPDATE` statements to write: the table, the result columns to set and the primary key
/// columns that find each row (their index in the result and their name in the table).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct UpdatePlan<'a> {
    pub table: &'a TableKeys,
    pub set: Vec<(usize, &'a str)>,
    pub keys: Vec<(usize, &'a str)>,
}

/// The table rows of a result update, when that is sure: the result must pass
/// the `INSERT` allowlist ([`insert_source`]: provably rows of exactly one table) and hold every
/// column of that table's primary key. The key columns find the row; every other column is
/// set, except generated ones (`GENERATED ALWAYS AS (…)` and `GENERATED ALWAYS AS IDENTITY`
/// take no value in an `UPDATE`).
pub fn update_source<'a>(
    d: Dialect,
    catalog: Option<&'a KeyCatalog>,
    origins: &[Option<ColumnOrigin>],
    names: &[&str],
    sql: &str,
) -> Result<UpdatePlan<'a>, NotUpdatable> {
    let plan = insert_source(d, catalog, origins, names, sql).map_err(NotUpdatable::NotInsertable)?;
    let table = plan.table;
    let pk: Vec<(&i16, &ColumnKeys)> = table.columns.iter().filter(|(_, c)| c.marks.pk).collect();
    if pk.is_empty() {
        return Err(NotUpdatable::NoPrimaryKey);
    }
    // Every result column is a column of `table` (the allowlist checked it).
    let number = |i: usize| origins[i].as_ref().and_then(|o| locate(catalog, o).ok()).map(|o| o.column);
    let missing: Vec<String> = pk
        .iter()
        .filter(|(n, _)| !(0..origins.len()).any(|i| number(i) == Some(**n)))
        .map(|(_, c)| c.name.clone())
        .collect();
    if !missing.is_empty() {
        return Err(NotUpdatable::MissingKey(missing));
    }
    let column = |i: usize| number(i).and_then(|n| table.columns.get(&n));
    let keys: Vec<(usize, &str)> =
        (0..origins.len()).filter_map(|i| column(i).filter(|c| c.marks.pk).map(|c| (i, c.name.as_str()))).collect();
    let set: Vec<(usize, &str)> = (0..origins.len())
        .filter_map(|i| column(i).filter(|c| !c.marks.pk && c.generated == Generated::No).map(|c| (i, c.name.as_str())))
        .collect();
    if set.is_empty() {
        return Err(NotUpdatable::NothingToSet);
    }
    Ok(UpdatePlan { table, set, keys })
}

/// `:copy insert <target>`: the rows go into the table the user names, result columns to the
/// table's columns of the same name. Refused when the table is not known, a result column has
/// no column of its name there, a name comes twice, or a column is `GENERATED ALWAYS AS (…)`.
/// `target` is `schema.table` or a table name found in one schema only; unquoted names fold
/// as dialect `d` folds them (PostgreSQL: to lower case), quoted ones are taken as they are.
pub fn insert_into<'a>(
    d: Dialect,
    catalog: Option<&'a KeyCatalog>,
    target: &str,
    names: &[&str],
) -> Result<InsertPlan<'a>, NotInsertable> {
    use NotInsertable::*;
    let catalog = catalog.ok_or(NoCatalog)?;
    let (schema, name) = table_name(d, target).ok_or(NoSuchTable)?;
    let table = catalog.find(schema.as_deref(), &name)?;
    distinct(names)?;
    let columns = names
        .iter()
        .map(|n| table.columns.values().find(|c| c.name == *n).ok_or_else(|| NoSuchColumn(n.to_string())))
        .collect::<Result<Vec<_>, _>>()?;
    if let Some(c) = columns.iter().find(|c| c.generated == Generated::Expression) {
        return Err(GeneratedColumn(c.name.clone()));
    }
    plan(table, columns)
}

fn distinct(names: &[&str]) -> Result<(), NotInsertable> {
    let mut seen = HashSet::new();
    if names.iter().all(|n| seen.insert(*n)) { Ok(()) } else { Err(NotInsertable::DuplicateNames) }
}

/// Write `cols` (the table column of each result column, in result order) into `table`.
fn plan<'a>(table: &'a TableKeys, cols: Vec<&'a ColumnKeys>) -> Result<InsertPlan<'a>, NotInsertable> {
    let skipped = cols.iter().filter(|c| c.generated == Generated::Expression).map(|c| c.name.as_str()).collect();
    let columns: Vec<(usize, &str)> = cols
        .iter()
        .enumerate()
        .filter(|(_, c)| c.generated != Generated::Expression)
        .map(|(i, c)| (i, c.name.as_str()))
        .collect();
    if columns.is_empty() {
        return Err(NotInsertable::OnlyGenerated);
    }
    let overriding = cols.iter().any(|c| c.generated == Generated::IdentityAlways);
    Ok(InsertPlan { table, columns, skipped, overriding })
}

/// The table a `FROM` clause names: `[schema.]name`, folded as the server folds it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FromTable {
    pub schema: Option<String>,
    pub name: String,
}

impl FromTable {
    /// Whether it names table `t` (without a schema, any schema: the search path is not known).
    fn names(&self, t: &TableKeys) -> bool {
        self.name == t.name && self.schema.as_ref().is_none_or(|s| *s == t.schema)
    }
}

/// The identifier token `t` names in dialect `d`: an unquoted word folded as the server folds
/// it ([`Dialect::fold`]), a quoted one unquoted (it must be closed).
fn ident(d: Dialect, t: &Token, sql: &str) -> Option<String> {
    let text = t.text(sql);
    match t.kind {
        Tok::QuotedIdent => d.unquote(text),
        Tok::Ident | Tok::Keyword => Some(d.fold(text)),
        _ => None,
    }
}

/// `schema.table` or `table`, as `:copy insert` takes it.
fn table_name(d: Dialect, s: &str) -> Option<(Option<String>, String)> {
    let toks: Vec<Token> = lex(s).into_iter().filter(|t| !t.is_trivia()).collect();
    match toks.as_slice() {
        [n] => Some((None, ident(d, n, s)?)),
        [sc, dot, n] if dot.kind == Tok::Dot => Some((Some(ident(d, sc, s)?), ident(d, n, s)?)),
        _ => None,
    }
}

/// The one table statement `sql` reads, if it is lexically a projection of one table's rows:
/// `SELECT … FROM [ONLY] [schema.]table [*] [[AS] alias] [WHERE …] [ORDER BY …] [LIMIT …] …`.
/// A subquery may filter (in `WHERE`), but not add rows or columns. Why not, otherwise. Names
/// are read as dialect `d` reads them.
pub fn single_table(d: Dialect, sql: &str) -> Result<FromTable, NotInsertable> {
    use NotInsertable::*;
    let mut toks: Vec<Token> = lex(sql).into_iter().filter(|t| !t.is_trivia()).collect();
    while toks.last().is_some_and(|t| t.kind == Tok::Semi) {
        toks.pop();
    }
    let word = |t: &Token, w: &str| t.is_word() && t.text(sql).eq_ignore_ascii_case(w);
    let any = |t: &Token, ws: &[&str]| ws.iter().any(|w| word(t, w));
    match toks.first() {
        Some(t) if word(t, "SELECT") => {}
        Some(t) if word(t, "WITH") => return Err(With),
        _ => return Err(NotSelect),
    }
    if toks.iter().any(|t| t.kind == Tok::Semi) {
        return Err(NotSelect);
    }
    if toks.iter().any(|t| word(t, "OVER")) {
        return Err(Window);
    }
    // How deep in parentheses each token is.
    let mut depth = 0i32;
    let depths: Vec<i32> = toks
        .iter()
        .map(|t| {
            depth -= i32::from(t.kind == Tok::RParen);
            let d = depth;
            depth += i32::from(t.kind == Tok::LParen);
            d
        })
        .collect();
    let top = |i: usize| depths[i] == 0;
    let from = (1..toks.len()).find(|&i| top(i) && word(&toks[i], "FROM"));
    for i in 1..from.unwrap_or(toks.len()) {
        let t = &toks[i];
        if word(t, "SELECT") {
            return Err(Subquery);
        }
        if top(i) && word(t, "INTO") {
            return Err(NotSelect);
        }
        if top(i) && word(t, "DISTINCT") && toks.get(i + 1).is_some_and(|n| word(n, "ON")) {
            return Err(Grouping);
        }
    }
    let from = from.ok_or(NotATable)?;
    const ENDS: &[&str] = &[
        "WHERE",
        "GROUP",
        "HAVING",
        "WINDOW",
        "ORDER",
        "LIMIT",
        "OFFSET",
        "FETCH",
        "FOR",
        "UNION",
        "INTERSECT",
        "EXCEPT",
    ];
    let end = (from + 1..toks.len()).find(|&i| top(i) && any(&toks[i], ENDS)).unwrap_or(toks.len());
    for t in toks.iter().enumerate().skip(end).filter(|(i, _)| top(*i)).map(|(_, t)| t) {
        if any(t, &["UNION", "INTERSECT", "EXCEPT"]) {
            return Err(SetOperation);
        }
        if any(t, &["GROUP", "HAVING"]) {
            return Err(Grouping);
        }
        if word(t, "WINDOW") {
            return Err(Window);
        }
    }
    let clause = &toks[from + 1..end];
    if clause.iter().any(|t| word(t, "SELECT")) {
        return Err(Subquery);
    }
    if clause.iter().any(|t| t.kind == Tok::LParen || any(t, &["LATERAL", "ROWS", "TABLESAMPLE", "VALUES"])) {
        return Err(NotATable);
    }
    if clause.iter().any(|t| t.kind == Tok::Comma || any(t, &["JOIN", "CROSS", "NATURAL"])) {
        return Err(SeveralTables);
    }
    let mut rest = clause;
    if rest.first().is_some_and(|t| word(t, "ONLY")) {
        rest = &rest[1..];
    }
    let (schema, name, rest) = match rest {
        [s, dot, n, rest @ ..] if dot.kind == Tok::Dot => {
            (Some(ident(d, s, sql).ok_or(NotATable)?), ident(d, n, sql), rest)
        }
        [n, rest @ ..] => (None, ident(d, n, sql), rest),
        [] => return Err(NotATable),
    };
    let name = name.ok_or(NotATable)?;
    let rest = match rest {
        [star, rest @ ..] if star.kind == Tok::Op && star.text(sql) == "*" => rest,
        _ => rest,
    };
    let alias_ok = match rest {
        [] => true,
        [a] => matches!(a.kind, Tok::Ident | Tok::QuotedIdent),
        [kw, a] => word(kw, "AS") && ident(d, a, sql).is_some(),
        _ => false,
    };
    if alias_ok { Ok(FromTable { schema, name }) } else { Err(NotATable) }
}

#[cfg(test)]
mod tests;
