//! The structure of one table (or view), for the explorer and a later DDL view: its columns,
//! keys, indexes, constraints and triggers, and the server's estimate of its size.
//!
//! A driver with `Capabilities::structure` reads it on its metadata session when the UI asks
//! (`DbCommand::LoadStructure`, when a table's node opens) from the catalog only: the table
//! itself is never read. Names and expressions are as the server prints them (PostgreSQL's
//! `pg_get_expr`, `pg_get_indexdef`); each constraint, index and trigger also keeps the
//! server's own definition text, which the DDL view can show as it is.

use super::keys::KeyMarks;

/// What kind of relation it is: which groups apply ([`RelationKind::groups`]).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RelationKind {
    Table,
    /// A table split into partitions (its size and rows are its partitions').
    PartitionedTable,
    ForeignTable,
    View,
    MaterializedView,
}

/// One group of a table's structure in the explorer.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum StructureGroup {
    Columns,
    PrimaryKey,
    ForeignKeys,
    Indexes,
    UniqueConstraints,
    CheckConstraints,
    Triggers,
}

impl RelationKind {
    /// The groups a relation of this kind can have, in the order they are shown: a table all of
    /// them, a view its columns and triggers (`INSTEAD OF`), a materialized view its columns and
    /// indexes, a foreign table its columns, checks and triggers.
    pub fn groups(self) -> &'static [StructureGroup] {
        use StructureGroup::*;
        match self {
            RelationKind::Table | RelationKind::PartitionedTable => {
                &[Columns, PrimaryKey, ForeignKeys, Indexes, UniqueConstraints, CheckConstraints, Triggers]
            }
            RelationKind::ForeignTable => &[Columns, CheckConstraints, Triggers],
            RelationKind::View => &[Columns, Triggers],
            RelationKind::MaterializedView => &[Columns, Indexes],
        }
    }

    /// It has storage of its own whose size and rows the server estimates.
    pub fn has_storage(self) -> bool {
        matches!(self, RelationKind::Table | RelationKind::PartitionedTable | RelationKind::MaterializedView)
    }
}

/// How the database fills a column it is not given.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub enum ColumnFill {
    /// Its default (`None`: none, so NULL).
    #[default]
    Default,
    /// `GENERATED ALWAYS AS (expression) STORED`.
    Stored(String),
    /// `GENERATED ALWAYS AS (expression) VIRTUAL` (PostgreSQL 18).
    Virtual(String),
    /// `GENERATED ALWAYS AS IDENTITY`.
    IdentityAlways,
    /// `GENERATED BY DEFAULT AS IDENTITY`.
    IdentityByDefault,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StructureColumn {
    pub name: String,
    /// The type as the server formats it (`character varying(20)`, `integer[]`).
    pub type_name: String,
    pub not_null: bool,
    /// The default expression, as the server prints it.
    pub default: Option<String>,
    pub fill: ColumnFill,
}

impl Index {
    /// Its key columns with their options, as the index's definition lists them
    /// (`created DESC`).
    pub fn keys(&self) -> Vec<String> {
        self.columns
            .iter()
            .enumerate()
            .map(|(i, c)| match self.options.get(i).filter(|o| !o.is_empty()) {
                Some(o) => format!("{c} {o}"),
                None => c.clone(),
            })
            .collect()
    }
}

/// A primary key or a unique constraint.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct KeyConstraint {
    pub name: String,
    pub columns: Vec<String>,
    /// The server's definition (`PRIMARY KEY (id)`).
    pub definition: String,
}

/// What a foreign key does when the row it references is deleted or updated.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum FkAction {
    #[default]
    NoAction,
    Restrict,
    Cascade,
    SetNull,
    SetDefault,
}

impl FkAction {
    /// The action as SQL writes it.
    pub fn sql(self) -> &'static str {
        match self {
            FkAction::NoAction => "NO ACTION",
            FkAction::Restrict => "RESTRICT",
            FkAction::Cascade => "CASCADE",
            FkAction::SetNull => "SET NULL",
            FkAction::SetDefault => "SET DEFAULT",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ForeignKey {
    pub name: String,
    pub columns: Vec<String>,
    /// The referenced table (in the same database: PostgreSQL has no foreign key to another).
    pub ref_schema: String,
    pub ref_table: String,
    pub ref_columns: Vec<String>,
    pub on_delete: FkAction,
    pub on_update: FkAction,
    pub definition: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Index {
    pub name: String,
    /// Its key columns, or the expressions it indexes, in order.
    pub columns: Vec<String>,
    /// For each key column, what the index says of it beyond the defaults, as SQL writes it
    /// after the column: its collation, operator class and order (`DESC`, `NULLS FIRST`,
    /// `COLLATE "C" text_pattern_ops`); empty when it has none.
    pub options: Vec<String>,
    /// Columns it only carries (`INCLUDE`).
    pub include: Vec<String>,
    pub unique: bool,
    /// Its access method (`btree`, `gin`, …).
    pub method: String,
    /// The predicate of a partial index.
    pub predicate: Option<String>,
    /// It backs the primary key.
    pub primary: bool,
    /// It backs a constraint (the primary key, a unique or an exclusion constraint).
    pub constraint: bool,
    /// The server's definition (`CREATE INDEX …`).
    pub definition: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CheckConstraint {
    pub name: String,
    /// The condition (`price >= 0::numeric`).
    pub expression: String,
    pub definition: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TriggerTiming {
    Before,
    After,
    InsteadOf,
}

impl TriggerTiming {
    pub fn sql(self) -> &'static str {
        match self {
            TriggerTiming::Before => "BEFORE",
            TriggerTiming::After => "AFTER",
            TriggerTiming::InsteadOf => "INSTEAD OF",
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TriggerEvent {
    Insert,
    Update,
    Delete,
    Truncate,
}

impl TriggerEvent {
    pub fn sql(self) -> &'static str {
        match self {
            TriggerEvent::Insert => "INSERT",
            TriggerEvent::Update => "UPDATE",
            TriggerEvent::Delete => "DELETE",
            TriggerEvent::Truncate => "TRUNCATE",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Trigger {
    pub name: String,
    pub timing: TriggerTiming,
    /// In the order `INSERT`, `UPDATE`, `DELETE`, `TRUNCATE`.
    pub events: Vec<TriggerEvent>,
    /// `FOR EACH ROW` (else `FOR EACH STATEMENT`).
    pub for_each_row: bool,
    /// The function it calls, as `schema.name`.
    pub function: String,
    /// It fires (PostgreSQL: not `DISABLE`d).
    pub enabled: bool,
    /// The columns of `UPDATE OF`: an `UPDATE` fires it only when it sets one of them (empty:
    /// any `UPDATE`).
    pub update_columns: Vec<String>,
    /// The condition of its `WHEN` clause, without the parentheses.
    pub condition: Option<String>,
    pub definition: String,
}

/// The structure of one relation. Every list is in the server's order: columns by position,
/// the rest by name.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TableStructure {
    pub kind: RelationKind,
    /// The server's estimate of its rows; `None` when it has none (never analyzed) or the
    /// relation has no storage.
    pub estimated_rows: Option<u64>,
    /// An estimate of its size on disk with indexes and TOAST, from the server's statistics
    /// (PostgreSQL: `relpages`, which `VACUUM` and `ANALYZE` keep, so it can be behind; reading
    /// the exact size would lock the table); `None` without storage or statistics.
    pub total_bytes: Option<u64>,
    pub columns: Vec<StructureColumn>,
    pub primary_key: Option<KeyConstraint>,
    pub foreign_keys: Vec<ForeignKey>,
    pub indexes: Vec<Index>,
    pub unique_constraints: Vec<KeyConstraint>,
    pub checks: Vec<CheckConstraint>,
    pub triggers: Vec<Trigger>,
}

impl TableStructure {
    /// An empty structure of a relation of kind `kind`.
    pub fn new(kind: RelationKind) -> Self {
        Self {
            kind,
            estimated_rows: None,
            total_bytes: None,
            columns: Vec::new(),
            primary_key: None,
            foreign_keys: Vec::new(),
            indexes: Vec::new(),
            unique_constraints: Vec::new(),
            checks: Vec::new(),
            triggers: Vec::new(),
        }
    }

    /// How many items group `g` has.
    pub fn count(&self, g: StructureGroup) -> usize {
        match g {
            StructureGroup::Columns => self.columns.len(),
            StructureGroup::PrimaryKey => usize::from(self.primary_key.is_some()),
            StructureGroup::ForeignKeys => self.foreign_keys.len(),
            StructureGroup::Indexes => self.indexes.len(),
            StructureGroup::UniqueConstraints => self.unique_constraints.len(),
            StructureGroup::CheckConstraints => self.checks.len(),
            StructureGroup::Triggers => self.triggers.len(),
        }
    }

    /// The keys column `column` is part of, as [`super::KeyCatalog`] marks them: the primary
    /// key, a foreign key, a unique constraint or a unique index on plain columns that is not
    /// partial (and not the primary key's).
    pub fn marks(&self, column: &str) -> KeyMarks {
        let has = |cols: &[String]| cols.iter().any(|c| c == column);
        let unique_index = self.indexes.iter().any(|i| {
            i.unique
                && !i.primary
                && i.predicate.is_none()
                && has(&i.columns)
                && i.columns.iter().all(|c| self.is_column(c))
        });
        KeyMarks {
            pk: self.primary_key.as_ref().is_some_and(|k| has(&k.columns)),
            fk: self.foreign_keys.iter().any(|f| has(&f.columns)),
            unique: unique_index || self.unique_constraints.iter().any(|u| has(&u.columns)),
        }
    }

    fn is_column(&self, name: &str) -> bool {
        self.columns.iter().any(|c| c.name == name)
    }
}

#[cfg(test)]
mod tests;
