use super::super::tests::{Case, at, check, typ};
use super::*;

/// `d`, `c` and `y` with every motion, counts before and after the operator, doubled
/// operators, `x X s S D C Y`, puts, and the ends of lines and of the text, as Vim does them.
#[test]
fn operators_over_motions_with_counts() {
    const CASES: &[Case] = &[
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dh",
            "one two\n  tree four\nfive six\nseven",
            (1, 3),
            Some(("h", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dl",
            "one two\n  thee four\nfive six\nseven",
            (1, 4),
            Some(("r", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dj",
            "one two\nseven",
            (1, 0),
            Some(("  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dk",
            "five six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dw",
            "one two\n  thfour\nfive six\nseven",
            (1, 4),
            Some(("ree ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "db",
            "one two\n  ree four\nfive six\nseven",
            (1, 2),
            Some(("th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "de",
            "one two\n  th four\nfive six\nseven",
            (1, 4),
            Some(("ree", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d0",
            "one two\nree four\nfive six\nseven",
            (1, 0),
            Some(("  th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d^",
            "one two\n  ree four\nfive six\nseven",
            (1, 2),
            Some(("th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d$",
            "one two\n  th\nfive six\nseven",
            (1, 3),
            Some(("ree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dgg",
            "five six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dG",
            "one two",
            (0, 0),
            Some(("  three four\nfive six\nseven", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d<Left>",
            "one two\n  tree four\nfive six\nseven",
            (1, 3),
            Some(("h", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d<Right>",
            "one two\n  thee four\nfive six\nseven",
            (1, 4),
            Some(("r", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d<Down>",
            "one two\nseven",
            (1, 0),
            Some(("  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d<Up>",
            "five six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d<Home>",
            "one two\nree four\nfive six\nseven",
            (1, 0),
            Some(("  th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d<End>",
            "one two\n  th\nfive six\nseven",
            (1, 3),
            Some(("ree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "ch_<Esc>",
            "one two\n  t_ree four\nfive six\nseven",
            (1, 3),
            Some(("h", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cl_<Esc>",
            "one two\n  th_ee four\nfive six\nseven",
            (1, 4),
            Some(("r", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cj_<Esc>",
            "one two\n  _\nseven",
            (1, 2),
            Some(("  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "ck_<Esc>",
            "_\nfive six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cw_<Esc>",
            "one two\n  th_ four\nfive six\nseven",
            (1, 4),
            Some(("ree", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cb_<Esc>",
            "one two\n  _ree four\nfive six\nseven",
            (1, 2),
            Some(("th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "ce_<Esc>",
            "one two\n  th_ four\nfive six\nseven",
            (1, 4),
            Some(("ree", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "c0_<Esc>",
            "one two\n_ree four\nfive six\nseven",
            (1, 0),
            Some(("  th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "c^_<Esc>",
            "one two\n  _ree four\nfive six\nseven",
            (1, 2),
            Some(("th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "c$_<Esc>",
            "one two\n  th_\nfive six\nseven",
            (1, 4),
            Some(("ree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cgg_<Esc>",
            "_\nfive six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cG_<Esc>",
            "one two\n  _",
            (1, 2),
            Some(("  three four\nfive six\nseven", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yh",
            "one two\n  three four\nfive six\nseven",
            (1, 3),
            Some(("h", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yl",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("r", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yj",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yk",
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yw",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("ree ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yb",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            Some(("th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "ye",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("ree", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "y0",
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            Some(("  th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "y^",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            Some(("th", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "y$",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("ree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "ygg",
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yG",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("  three four\nfive six\nseven", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "dd",
            "one two\nfive six\nseven",
            (1, 0),
            Some(("  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "cc_<Esc>",
            "one two\n  _\nfive six\nseven",
            (1, 2),
            Some(("  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yy",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "3dd",
            "seven",
            (0, 0),
            Some(("one two\n  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "5dd",
            "one two",
            (0, 0),
            Some(("  three four\nfive six\nseven", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "2yy",
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "2cc_<Esc>",
            "_\nfive six\nseven",
            (0, 0),
            Some(("one two\n  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "d2w",
            "\n  three four\nfive six\nseven",
            (0, 0),
            Some(("one two", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "2dw",
            "\n  three four\nfive six\nseven",
            (0, 0),
            Some(("one two", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "2d3w",
            "seven",
            (0, 0),
            Some(("one two\n  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "d3e",
            " four\nfive six\nseven",
            (0, 0),
            Some(("one two\n  three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 5),
            "d2b",
            "one two\n  three six\nseven",
            (1, 8),
            Some(("four\nfive ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 3),
            "3x",
            "one two\n  te four\nfive six\nseven",
            (1, 3),
            Some(("hre", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 3),
            "9x",
            "one two\n  t\nfive six\nseven",
            (1, 2),
            Some(("hree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 3),
            "2X",
            "one two\n hree four\nfive six\nseven",
            (1, 1),
            Some((" t", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "d3G",
            "seven",
            (0, 0),
            Some(("one two\n  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "D",
            "one two\n  th\nfive six\nseven",
            (1, 3),
            Some(("ree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "2D",
            "one two\n  th\nseven",
            (1, 3),
            Some(("ree four\nfive six", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "C_<Esc>",
            "one two\n  th_\nfive six\nseven",
            (1, 4),
            Some(("ree four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "Y",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "2Y",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            Some(("  three four\nfive six", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "s_<Esc>",
            "one two\n  th_ee four\nfive six\nseven",
            (1, 4),
            Some(("r", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "2s_<Esc>",
            "one two\n  th_e four\nfive six\nseven",
            (1, 4),
            Some(("re", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "S_<Esc>",
            "one two\n  _\nfive six\nseven",
            (1, 2),
            Some(("  three four", true)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d2$",
            "one two\n  th\nseven",
            (1, 3),
            Some(("ree four\nfive six", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 1),
            "d2$",
            "one two\n  three four\nfive six\nseven",
            (3, 1),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 1),
            "dj",
            "one two\n  three four\nfive six\nseven",
            (3, 1),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 1),
            "dk",
            "one two\n  three four\nfive six\nseven",
            (0, 1),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "dh",
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 6),
            "dl",
            "one tw\n  three four\nfive six\nseven",
            (0, 5),
            Some(("o", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "dw",
            "one \n  three four\nfive six\nseven",
            (0, 3),
            Some(("two", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 5),
            "cw_<Esc>",
            "one t_\n  three four\nfive six\nseven",
            (0, 5),
            Some(("wo", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 6),
            "cw_<Esc>",
            "one tw_\n  three four\nfive six\nseven",
            (0, 6),
            Some(("o", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "c2w_<Esc>",
            "one _ four\nfive six\nseven",
            (0, 4),
            Some(("two\n  three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 3),
            "cw_<Esc>",
            "one_two\n  three four\nfive six\nseven",
            (0, 3),
            Some((" ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "3dw",
            "one \nfive six\nseven",
            (0, 3),
            Some(("two\n  three four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 2),
            "dw",
            "one two\n  three four\nfive six\nse",
            (3, 1),
            Some(("ven", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 4),
            "dw",
            "one two\n  three four\nfive six\nseve",
            (3, 3),
            Some(("n", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 4),
            "x",
            "one two\n  three four\nfive six\nseve",
            (3, 3),
            Some(("n", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 4),
            "de",
            "one two\n  three four\nfive six\nseve",
            (3, 3),
            Some(("n", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "db",
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            None,
        ),
        ("a\n\nb", (1, 0), "dw", "a\nb", (1, 0), Some(("", true))),
        ("a\n\nb", (1, 0), "cw_<Esc>", "a\n_\nb", (1, 0), Some(("", true))),
        ("a\n\nb", (1, 0), "x", "a\n\nb", (1, 0), None),
        ("a\n\nb", (1, 0), "D", "a\n\nb", (1, 0), None),
        ("a\n\nb", (1, 0), "dd", "a\nb", (1, 0), Some(("", true))),
        ("a\n\nb", (1, 0), "s_<Esc>", "a\n_\nb", (1, 0), None),
        ("a\n\nb", (1, 0), "C_<Esc>", "a\n_\nb", (1, 0), Some(("", false))),
        ("x = 1;\n\ny = 2", (0, 4), "dw", "x = ;\n\ny = 2", (0, 4), Some(("1", false))),
        ("x = 1;\n\ny = 2", (0, 0), "d3w", ";\n\ny = 2", (0, 0), Some(("x = 1", false))),
        ("x = 1;\n\ny = 2", (0, 2), "d4w", "x \ny = 2", (0, 1), Some(("= 1;\n", false))),
        ("foo(bar, baz)", (0, 0), "d2w", "bar, baz)", (0, 0), Some(("foo(", false))),
        ("  indented line\nnext", (0, 2), "dw", "  line\nnext", (0, 2), Some(("indented ", false))),
        ("  indented line\nnext", (0, 10), "dw", "  indentedline\nnext", (0, 10), Some((" ", false))),
        ("  indented line\nnext", (0, 10), "d2w", "  indented\nnext", (0, 9), Some((" line", false))),
        ("  indented line\nnext", (0, 0), "d2w", "line\nnext", (0, 0), Some(("  indented ", false))),
        ("  indented line\nnext", (0, 4), "d2w", "  in\nnext", (0, 3), Some(("dented line", false))),
        ("one\ntwo", (0, 1), "yyp", "one\none\ntwo", (1, 0), Some(("one", true))),
        ("one\ntwo", (0, 1), "yyP", "one\none\ntwo", (0, 0), Some(("one", true))),
        ("one\ntwo", (0, 1), "yy3p", "one\none\none\none\ntwo", (1, 0), Some(("one", true))),
        ("one\ntwo", (1, 1), "ywP", "one\ntwowo", (1, 2), Some(("wo", false))),
        ("one\ntwo", (1, 1), "yw2p", "one\ntwwowoo", (1, 5), Some(("wo", false))),
        ("one\ntwo", (0, 0), "ddp", "two\none", (1, 0), Some(("one", true))),
        ("one\ntwo\nthree", (2, 0), "ddP", "one\nthree\ntwo", (1, 0), Some(("three", true))),
        ("one\ntwo\nthree", (0, 1), "xp", "oen\ntwo\nthree", (0, 2), Some(("n", false))),
        ("one\ntwo\nthree", (0, 0), "d2d", "three", (0, 0), Some(("one\ntwo", true))),
        ("one\ntwo\nthree", (0, 0), "2d2d", "", (0, 0), Some(("one\ntwo\nthree", true))),
    ];
    check(CASES);
}

/// A count is typed before an operator, after it, or both (they multiply); `0` is a motion
/// unless a count is being typed, and a count too large for the text stops at its end.
#[test]
fn counts() {
    let text = "l1\nl2\nl3\nl4\nl5\nl6\nl7\nl8\nl9\nl10\nl11\nl12";
    let mut e = Editor::new(text);
    typ(&mut e, "10G");
    assert_eq!(e.row, 9);
    typ(&mut e, "gg2d3d");
    assert_eq!(e.lines.len(), 6, "2d3d = 6 lines");
    typ(&mut e, "u10j");
    assert_eq!(e.row, 10);
    typ(&mut e, "999999999k");
    assert_eq!(e.row, 0, "a huge count stops at the first line");
    typ(&mut e, "$10x");
    assert_eq!(e.lines[0], "l", "x from the last grapheme");
    typ(&mut e, "u0");
    assert_eq!(e.col, 0);
    typ(&mut e, "j$");
    typ(&mut e, "10");
    typ(&mut e, "G");
    assert_eq!(e.row, 9, "0 after a digit is part of the count");
}

/// Keys that do not finish a command cancel it: nothing changes and the next command starts
/// fresh.
#[test]
fn unfinished_commands_are_cancelled() {
    let text = "one two three";
    let mut e = Editor::new(text);
    for keys in ["d<Esc>", "dz", "3<Esc>", "g<Esc>", "gz", "dgz", "c<Esc>", "y<C-x>"] {
        typ(&mut e, keys);
        assert_eq!((e.text().as_str(), e.mode, e.awaiting_key()), (text, Mode::Normal, false), "{keys}");
    }
    typ(&mut e, "dw");
    assert_eq!(e.text(), "two three", "no count left over");
}

/// `p` puts nothing when the register is empty, and refuses copies that would be too big.
#[test]
fn put_needs_a_register_and_a_sane_size() {
    let mut e = Editor::new("abc");
    typ(&mut e, "p");
    assert_eq!(e.text(), "abc");
    let big = "x".repeat(1 << 20);
    let mut e = at(&big, (0, 0));
    typ(&mut e, "y$99999p");
    assert_eq!(e.len_bytes(), 1 << 20, "100 GB are not put");
}
