//! The built-in themes other than [`super::DARK`]. The palettes of the named themes are their
//! projects' own (each credited above its constants); a color moved from its palette for
//! contrast says so. Every theme passes the checks of `theme/tests.rs`.

use super::{Dim, Theme, rgb};
use ratatui::style::{Color, Modifier, Style};

/// The terminal's own colors: its foreground and background, and the 16 ANSI colors by role
/// (errors red, warnings yellow, …), so the terminal's palette decides how they look. A selection
/// is reversed text, the statement tint is off (its gutter bar stays), and the screen behind a
/// dialog is dimmed with [`Modifier::DIM`].
pub const TERMINAL: Theme = Theme {
    bg: Color::Reset,
    surface: Color::Reset,
    surface_alt: Color::Reset,
    border: Color::DarkGray,
    accent: Color::Cyan,
    accent_warm: Color::Magenta,
    fg: Color::Reset,
    fg_muted: Color::DarkGray,
    fg_dim: Color::DarkGray,
    selection: Style::new().add_modifier(Modifier::REVERSED),
    range: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD),
    cursor_line: Style::new().add_modifier(Modifier::UNDERLINED),
    current_stmt: Style::new(),
    current_stmt_bar: Color::Blue,
    success: Color::Green,
    warning: Color::Yellow,
    error: Color::Red,
    null_fg: Color::DarkGray,
    syn_keyword: Style::new().fg(Color::Blue).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(Color::Cyan),
    syn_string: Style::new().fg(Color::Green),
    syn_number: Style::new().fg(Color::Magenta),
    syn_comment: Style::new().fg(Color::DarkGray).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new(),
    syn_identifier: Style::new(),
    syn_quoted_ident: Style::new().fg(Color::Cyan),
    key_pk: Color::Yellow,
    key_fk: Color::Blue,
    key_uq: Color::Magenta,
    mode_normal: Color::Blue,
    mode_insert: Color::Green,
    mode_visual: Color::Magenta,
    mode_command: Color::Yellow,
    mode_fg: Color::Black,
    search_match: Style::new().fg(Color::Black).bg(Color::Yellow),
    match_paren: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD.union(Modifier::UNDERLINED)),
    read_only_mark: Style::new().fg(Color::Cyan).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(Color::Red).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(Color::Magenta).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(Color::Yellow).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Modifier,
};

/// The light truecolor theme: dark text on an off-white background.
pub const LIGHT: Theme = Theme {
    bg: rgb(0xFBFBFC),
    surface: rgb(0xF1F3F6),
    surface_alt: rgb(0xF4F5F7),
    border: rgb(0xC9CED6),
    accent: rgb(0x0A7E78),
    accent_warm: rgb(0xA45A00),
    fg: rgb(0x1F2328),
    fg_muted: rgb(0x59636E),
    fg_dim: rgb(0x818B98),
    selection: Style::new().bg(rgb(0xD5E3F0)),
    range: Style::new().bg(rgb(0xDDEDEA)),
    cursor_line: Style::new().bg(rgb(0xEBEEF3)),
    current_stmt: Style::new().bg(rgb(0xF3F5F8)),
    current_stmt_bar: rgb(0x2E8078),
    success: rgb(0x1A7F37),
    warning: rgb(0x8A6100),
    error: rgb(0xC0262D),
    null_fg: rgb(0x818B98),
    syn_keyword: Style::new().fg(rgb(0x7C3AED)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x0550AE)),
    syn_string: Style::new().fg(rgb(0x116329)),
    syn_number: Style::new().fg(rgb(0xA45A00)),
    syn_comment: Style::new().fg(rgb(0x6E7781)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0x57606A)),
    syn_identifier: Style::new().fg(rgb(0x1F2328)),
    syn_quoted_ident: Style::new().fg(rgb(0x0A7E78)),
    key_pk: rgb(0x8A6100),
    key_fk: rgb(0x0550AE),
    key_uq: rgb(0x8250DF),
    mode_normal: rgb(0x0550AE),
    mode_insert: rgb(0x1A7F37),
    mode_visual: rgb(0x8250DF),
    mode_command: rgb(0xBC4C00),
    mode_fg: rgb(0xFFFFFF),
    search_match: Style::new().fg(rgb(0xFBFBFC)).bg(rgb(0xA45A00)),
    match_paren: Style::new().bg(rgb(0xC9CED6)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x0A7E78)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xC0262D)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xA45A00)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0x8A6100)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x808080), keep: 55 },
};

/// White text on black, saturated marks, a strong selection.
pub const HIGH_CONTRAST: Theme = Theme {
    bg: rgb(0x0A0A0A),
    surface: rgb(0x1C1C1C),
    surface_alt: rgb(0x141414),
    border: rgb(0xFFFFFF),
    accent: rgb(0x00E5FF),
    accent_warm: rgb(0xFFB000),
    fg: rgb(0xFFFFFF),
    fg_muted: rgb(0xD0D0D0),
    fg_dim: rgb(0xA8A8A8),
    selection: Style::new().bg(rgb(0x0033CC)),
    range: Style::new().bg(rgb(0x004D40)),
    cursor_line: Style::new().bg(rgb(0x262626)),
    current_stmt: Style::new().bg(rgb(0x121212)),
    current_stmt_bar: rgb(0x00E5FF),
    success: rgb(0x00FF66),
    warning: rgb(0xFFFF00),
    error: rgb(0xFF4040),
    null_fg: rgb(0xA8A8A8),
    syn_keyword: Style::new().fg(rgb(0xFF66FF)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x66B3FF)),
    syn_string: Style::new().fg(rgb(0x7CFF7C)),
    syn_number: Style::new().fg(rgb(0xFFB000)),
    syn_comment: Style::new().fg(rgb(0xBFBFBF)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0xFFFFFF)),
    syn_identifier: Style::new().fg(rgb(0xFFFFFF)),
    syn_quoted_ident: Style::new().fg(rgb(0x00E5FF)),
    key_pk: rgb(0xFFFF00),
    key_fk: rgb(0x66B3FF),
    key_uq: rgb(0xFF66FF),
    mode_normal: rgb(0x66B3FF),
    mode_insert: rgb(0x00FF66),
    mode_visual: rgb(0xFF66FF),
    mode_command: rgb(0xFFB000),
    mode_fg: rgb(0x000000),
    search_match: Style::new().fg(rgb(0x0A0A0A)).bg(rgb(0xFFB000)),
    match_paren: Style::new().bg(rgb(0xFFFFFF)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x00E5FF)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xFF4040)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xFFB000)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xFFFF00)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x000000), keep: 55 },
};

// Catppuccin (github.com/catppuccin/catppuccin, MIT): the palette of Mocha and Latte.
/// Catppuccin Mocha, the dark flavor.
pub const CATPPUCCIN_MOCHA: Theme = Theme {
    bg: rgb(0x1E1E2E),
    surface: rgb(0x313244),
    surface_alt: rgb(0x181825),
    border: rgb(0x45475A),
    accent: rgb(0x89B4FA),
    accent_warm: rgb(0xFAB387),
    fg: rgb(0xCDD6F4),
    fg_muted: rgb(0x7F849C),
    fg_dim: rgb(0x6C7086),
    selection: Style::new().bg(rgb(0x45475A)),
    range: Style::new().bg(rgb(0x2B3A52)),
    cursor_line: Style::new().bg(rgb(0x2A2B3C)),
    current_stmt: Style::new().bg(rgb(0x232334)),
    current_stmt_bar: rgb(0x7F849C),
    success: rgb(0xA6E3A1),
    warning: rgb(0xF9E2AF),
    error: rgb(0xF38BA8),
    null_fg: rgb(0x6C7086),
    syn_keyword: Style::new().fg(rgb(0xCBA6F7)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x89B4FA)),
    syn_string: Style::new().fg(rgb(0xA6E3A1)),
    syn_number: Style::new().fg(rgb(0xFAB387)),
    syn_comment: Style::new().fg(rgb(0x6C7086)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0x89DCEB)),
    syn_identifier: Style::new().fg(rgb(0xCDD6F4)),
    syn_quoted_ident: Style::new().fg(rgb(0x94E2D5)),
    key_pk: rgb(0xF9E2AF),
    key_fk: rgb(0x89B4FA),
    key_uq: rgb(0xCBA6F7),
    mode_normal: rgb(0x89B4FA),
    mode_insert: rgb(0xA6E3A1),
    mode_visual: rgb(0xCBA6F7),
    mode_command: rgb(0xFAB387),
    mode_fg: rgb(0x11111B),
    search_match: Style::new().fg(rgb(0x1E1E2E)).bg(rgb(0xFAB387)),
    match_paren: Style::new().bg(rgb(0x45475A)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x89B4FA)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xF38BA8)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xFAB387)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xF9E2AF)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x101019), keep: 57 },
};

/// Catppuccin Latte, the light flavor.
/// Moved from the palette so text and marks keep their contrast: `warning` (palette `#DF8E1D`),
/// `success` (palette `#40A02B`), `accent_warm` (palette `#FE640B`), `key_pk` (palette `#DF8E1D`),
/// `key_fk` (palette `#1E66F5`), `key_uq` (palette `#8839EF`).
pub const CATPPUCCIN_LATTE: Theme = Theme {
    bg: rgb(0xEFF1F5),
    surface: rgb(0xE6E9EF),
    surface_alt: rgb(0xDCE0E8),
    border: rgb(0xBCC0CC),
    accent: rgb(0x1E66F5),
    accent_warm: rgb(0xD85509),
    fg: rgb(0x4C4F69),
    fg_muted: rgb(0x6C6F85),
    fg_dim: rgb(0x8C8FA1),
    selection: Style::new().bg(rgb(0xCCD0DA)),
    range: Style::new().bg(rgb(0xD4DCEE)),
    cursor_line: Style::new().bg(rgb(0xE3E6ED)),
    current_stmt: Style::new().bg(rgb(0xEAECF2)),
    current_stmt_bar: rgb(0x6C6F85),
    success: rgb(0x3A9027),
    warning: rgb(0xB07017),
    error: rgb(0xD20F39),
    null_fg: rgb(0x8C8FA1),
    syn_keyword: Style::new().fg(rgb(0x8839EF)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x1E66F5)),
    syn_string: Style::new().fg(rgb(0x40A02B)),
    syn_number: Style::new().fg(rgb(0xFE640B)),
    syn_comment: Style::new().fg(rgb(0x8C8FA1)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0x04A5E5)),
    syn_identifier: Style::new().fg(rgb(0x4C4F69)),
    syn_quoted_ident: Style::new().fg(rgb(0x179299)),
    key_pk: rgb(0x8A5812),
    key_fk: rgb(0x1A5AD8),
    key_uq: rgb(0x7E35DE),
    mode_normal: rgb(0x209FB5),
    mode_insert: rgb(0x40A02B),
    mode_visual: rgb(0xEA76CB),
    mode_command: rgb(0xFE640B),
    mode_fg: rgb(0x11111B),
    search_match: Style::new().fg(rgb(0xEFF1F5)).bg(rgb(0xFE640B)),
    match_paren: Style::new().bg(rgb(0xBCC0CC)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x1E66F5)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xD20F39)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xD85509)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xB07017)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x808080), keep: 78 },
};

// Tokyo Night (github.com/enkia/tokyo-night-vscode-theme, MIT; the Day style as in
// github.com/folke/tokyonight.nvim).
/// Tokyo Night, the dark style.
pub const TOKYO_NIGHT_NIGHT: Theme = Theme {
    bg: rgb(0x1A1B26),
    surface: rgb(0x1F2335),
    surface_alt: rgb(0x16161E),
    border: rgb(0x414868),
    accent: rgb(0x7AA2F7),
    accent_warm: rgb(0xFF9E64),
    fg: rgb(0xC0CAF5),
    fg_muted: rgb(0x737AA2),
    fg_dim: rgb(0x565F89),
    selection: Style::new().bg(rgb(0x394B70)),
    range: Style::new().bg(rgb(0x283457)),
    cursor_line: Style::new().bg(rgb(0x292E42)),
    current_stmt: Style::new().bg(rgb(0x1E202E)),
    current_stmt_bar: rgb(0x737AA2),
    success: rgb(0x9ECE6A),
    warning: rgb(0xE0AF68),
    error: rgb(0xF7768E),
    null_fg: rgb(0x565F89),
    syn_keyword: Style::new().fg(rgb(0xBB9AF7)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x7AA2F7)),
    syn_string: Style::new().fg(rgb(0x9ECE6A)),
    syn_number: Style::new().fg(rgb(0xFF9E64)),
    syn_comment: Style::new().fg(rgb(0x565F89)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0x89DDFF)),
    syn_identifier: Style::new().fg(rgb(0xC0CAF5)),
    syn_quoted_ident: Style::new().fg(rgb(0x7DCFFF)),
    key_pk: rgb(0xE0AF68),
    key_fk: rgb(0x7AA2F7),
    key_uq: rgb(0xBB9AF7),
    mode_normal: rgb(0x7AA2F7),
    mode_insert: rgb(0x9ECE6A),
    mode_visual: rgb(0xBB9AF7),
    mode_command: rgb(0xFF9E64),
    mode_fg: rgb(0x15161E),
    search_match: Style::new().fg(rgb(0x1A1B26)).bg(rgb(0xFF9E64)),
    match_paren: Style::new().bg(rgb(0x414868)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x7AA2F7)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xF7768E)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xFF9E64)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xE0AF68)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x0E0F15), keep: 60 },
};

/// Tokyo Night Day, the light style.
/// Moved from the palette so text and marks keep their contrast: `fg` (palette `#3760BF`), `accent`
/// (palette `#2E7DE9`), `key_pk` (palette `#8C6C3E`), `key_fk` (palette `#2E7DE9`), `key_uq`
/// (palette `#9854F1`), `mode_normal` (palette `#2E7DE9`), `mode_visual` (palette `#D20065`),
/// `mode_command` (palette `#B15C00`), `mode_insert` (palette `#587539`).
pub const TOKYO_NIGHT_DAY: Theme = Theme {
    bg: rgb(0xE1E2E7),
    surface: rgb(0xECEEF3),
    surface_alt: rgb(0xD8DAE3),
    border: rgb(0xA8AECB),
    accent: rgb(0x2D7AE3),
    accent_warm: rgb(0xB15C00),
    fg: rgb(0x2E4B91),
    fg_muted: rgb(0x68709A),
    fg_dim: rgb(0x848CB5),
    selection: Style::new().bg(rgb(0xB7C1E3)),
    range: Style::new().bg(rgb(0xC4C8DA)),
    cursor_line: Style::new().bg(rgb(0xD0D5E3)),
    current_stmt: Style::new().bg(rgb(0xDADCE4)),
    current_stmt_bar: rgb(0x68709A),
    success: rgb(0x587539),
    warning: rgb(0x8C6C3E),
    error: rgb(0xC64343),
    null_fg: rgb(0x848CB5),
    syn_keyword: Style::new().fg(rgb(0x9854F1)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x2E7DE9)),
    syn_string: Style::new().fg(rgb(0x587539)),
    syn_number: Style::new().fg(rgb(0xB15C00)),
    syn_comment: Style::new().fg(rgb(0x848CB5)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0x006A83)),
    syn_identifier: Style::new().fg(rgb(0x2E4B91)),
    syn_quoted_ident: Style::new().fg(rgb(0x007197)),
    key_pk: rgb(0x745B39),
    key_fk: rgb(0x285FAD),
    key_uq: rgb(0x7645BA),
    mode_normal: rgb(0x2759A1),
    mode_insert: rgb(0x4A6135),
    mode_visual: rgb(0xB1055A),
    mode_command: rgb(0x884A0A),
    mode_fg: rgb(0xE1E2E7),
    search_match: Style::new().fg(rgb(0xE1E2E7)).bg(rgb(0xB15C00)),
    match_paren: Style::new().bg(rgb(0xA8AECB)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x2E7DE9)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xC64343)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xB15C00)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0x8C6C3E)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x808080), keep: 79 },
};

// Gruvbox (github.com/morhetz/gruvbox, MIT).
/// Gruvbox dark (medium contrast).
pub const GRUVBOX_DARK: Theme = Theme {
    bg: rgb(0x282828),
    surface: rgb(0x32302F),
    surface_alt: rgb(0x1D2021),
    border: rgb(0x504945),
    accent: rgb(0x83A598),
    accent_warm: rgb(0xFE8019),
    fg: rgb(0xEBDBB2),
    fg_muted: rgb(0xA89984),
    fg_dim: rgb(0x7C6F64),
    selection: Style::new().bg(rgb(0x504945)),
    range: Style::new().bg(rgb(0x45403D)),
    cursor_line: Style::new().bg(rgb(0x3C3836)),
    current_stmt: Style::new().bg(rgb(0x2E2C2B)),
    current_stmt_bar: rgb(0xA89984),
    success: rgb(0xB8BB26),
    warning: rgb(0xFABD2F),
    error: rgb(0xFB4934),
    null_fg: rgb(0x7C6F64),
    syn_keyword: Style::new().fg(rgb(0xFB4934)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x8EC07C)),
    syn_string: Style::new().fg(rgb(0xB8BB26)),
    syn_number: Style::new().fg(rgb(0xD3869B)),
    syn_comment: Style::new().fg(rgb(0x928374)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0xFE8019)),
    syn_identifier: Style::new().fg(rgb(0xEBDBB2)),
    syn_quoted_ident: Style::new().fg(rgb(0x83A598)),
    key_pk: rgb(0xFABD2F),
    key_fk: rgb(0x83A598),
    key_uq: rgb(0xD3869B),
    mode_normal: rgb(0x83A598),
    mode_insert: rgb(0xB8BB26),
    mode_visual: rgb(0xD3869B),
    mode_command: rgb(0xFE8019),
    mode_fg: rgb(0x282828),
    search_match: Style::new().fg(rgb(0x282828)).bg(rgb(0xFE8019)),
    match_paren: Style::new().bg(rgb(0x504945)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x83A598)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xFB4934)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xFE8019)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xFABD2F)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x161616), keep: 57 },
};

/// Gruvbox light (medium contrast).
/// Moved from the palette so text and marks keep their contrast: `key_pk` (palette `#AF3A03`),
/// `warning` (palette `#B57614`), `mode_insert` (palette `#79740E`).
pub const GRUVBOX_LIGHT: Theme = Theme {
    bg: rgb(0xFBF1C7),
    surface: rgb(0xF2E5BC),
    surface_alt: rgb(0xEBDBB2),
    border: rgb(0xD5C4A1),
    accent: rgb(0x076678),
    accent_warm: rgb(0xAF3A03),
    fg: rgb(0x3C3836),
    fg_muted: rgb(0x7C6F64),
    fg_dim: rgb(0x928374),
    selection: Style::new().bg(rgb(0xD5C4A1)),
    range: Style::new().bg(rgb(0xE4D6AE)),
    cursor_line: Style::new().bg(rgb(0xEBDBB2)),
    current_stmt: Style::new().bg(rgb(0xF5EBC2)),
    current_stmt_bar: rgb(0x7C6F64),
    success: rgb(0x79740E),
    warning: rgb(0xAA7016),
    error: rgb(0x9D0006),
    null_fg: rgb(0x928374),
    syn_keyword: Style::new().fg(rgb(0x9D0006)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x427B58)),
    syn_string: Style::new().fg(rgb(0x79740E)),
    syn_number: Style::new().fg(rgb(0x8F3F71)),
    syn_comment: Style::new().fg(rgb(0x928374)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0xAF3A03)),
    syn_identifier: Style::new().fg(rgb(0x3C3836)),
    syn_quoted_ident: Style::new().fg(rgb(0x076678)),
    key_pk: rgb(0xAC3A04),
    key_fk: rgb(0x076678),
    key_uq: rgb(0x8F3F71),
    mode_normal: rgb(0x076678),
    mode_insert: rgb(0x716C11),
    mode_visual: rgb(0x8F3F71),
    mode_command: rgb(0xAF3A03),
    mode_fg: rgb(0xFBF1C7),
    search_match: Style::new().fg(rgb(0xFBF1C7)).bg(rgb(0xAF3A03)),
    match_paren: Style::new().bg(rgb(0xD5C4A1)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x076678)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0x9D0006)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xAF3A03)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xAA7016)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x606060), keep: 60 },
};

// Nord (nordtheme.com, github.com/nordtheme/nord, MIT).
/// Nord.
/// Moved from the palette so text and marks keep their contrast: `key_uq` (palette `#B48EAD`),
/// `error` (palette `#BF616A`), `mode_fg` (palette `#2E3440`).
pub const NORD: Theme = Theme {
    bg: rgb(0x2E3440),
    surface: rgb(0x3B4252),
    surface_alt: rgb(0x353B49),
    border: rgb(0x4C566A),
    accent: rgb(0x88C0D0),
    accent_warm: rgb(0xD08770),
    fg: rgb(0xD8DEE9),
    fg_muted: rgb(0x9AA3B5),
    fg_dim: rgb(0x616E88),
    selection: Style::new().bg(rgb(0x434C5E)),
    range: Style::new().bg(rgb(0x3B4A5A)),
    cursor_line: Style::new().bg(rgb(0x3B4252)),
    current_stmt: Style::new().bg(rgb(0x323846)),
    current_stmt_bar: rgb(0x81A1C1),
    success: rgb(0xA3BE8C),
    warning: rgb(0xEBCB8B),
    error: rgb(0xC7767D),
    null_fg: rgb(0x616E88),
    syn_keyword: Style::new().fg(rgb(0x81A1C1)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x88C0D0)),
    syn_string: Style::new().fg(rgb(0xA3BE8C)),
    syn_number: Style::new().fg(rgb(0xB48EAD)),
    syn_comment: Style::new().fg(rgb(0x616E88)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0x81A1C1)),
    syn_identifier: Style::new().fg(rgb(0xD8DEE9)),
    syn_quoted_ident: Style::new().fg(rgb(0x8FBCBB)),
    key_pk: rgb(0xEBCB8B),
    key_fk: rgb(0x88C0D0),
    key_uq: rgb(0xC3A5BD),
    mode_normal: rgb(0x88C0D0),
    mode_insert: rgb(0xA3BE8C),
    mode_visual: rgb(0xB48EAD),
    mode_command: rgb(0xD08770),
    mode_fg: rgb(0x22262F),
    search_match: Style::new().fg(rgb(0x2E3440)).bg(rgb(0xD08770)),
    match_paren: Style::new().bg(rgb(0x4C566A)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0x88C0D0)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xBF616A)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xD08770)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xEBCB8B)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x191D23), keep: 61 },
};

// Dracula (draculatheme.com, github.com/dracula/dracula-theme, MIT).
/// Dracula.
pub const DRACULA: Theme = Theme {
    bg: rgb(0x282A36),
    surface: rgb(0x343746),
    surface_alt: rgb(0x21222C),
    border: rgb(0x44475A),
    accent: rgb(0xBD93F9),
    accent_warm: rgb(0xFFB86C),
    fg: rgb(0xF8F8F2),
    fg_muted: rgb(0x8C96BF),
    fg_dim: rgb(0x6272A4),
    selection: Style::new().bg(rgb(0x44475A)),
    range: Style::new().bg(rgb(0x3B3F55)),
    cursor_line: Style::new().bg(rgb(0x343746)),
    current_stmt: Style::new().bg(rgb(0x2D2F3D)),
    current_stmt_bar: rgb(0xBD93F9),
    success: rgb(0x50FA7B),
    warning: rgb(0xF1FA8C),
    error: rgb(0xFF5555),
    null_fg: rgb(0x6272A4),
    syn_keyword: Style::new().fg(rgb(0xFF79C6)).add_modifier(Modifier::BOLD),
    syn_function: Style::new().fg(rgb(0x50FA7B)),
    syn_string: Style::new().fg(rgb(0xF1FA8C)),
    syn_number: Style::new().fg(rgb(0xBD93F9)),
    syn_comment: Style::new().fg(rgb(0x6272A4)).add_modifier(Modifier::ITALIC),
    syn_operator: Style::new().fg(rgb(0xFF79C6)),
    syn_identifier: Style::new().fg(rgb(0xF8F8F2)),
    syn_quoted_ident: Style::new().fg(rgb(0x8BE9FD)),
    key_pk: rgb(0xFFB86C),
    key_fk: rgb(0x8BE9FD),
    key_uq: rgb(0xBD93F9),
    mode_normal: rgb(0xBD93F9),
    mode_insert: rgb(0x50FA7B),
    mode_visual: rgb(0xFF79C6),
    mode_command: rgb(0xFFB86C),
    mode_fg: rgb(0x282A36),
    search_match: Style::new().fg(rgb(0x282A36)).bg(rgb(0xFFB86C)),
    match_paren: Style::new().bg(rgb(0x44475A)).add_modifier(Modifier::BOLD),
    read_only_mark: Style::new().fg(rgb(0xBD93F9)).add_modifier(Modifier::BOLD),
    danger_mark: Style::new().fg(rgb(0xFF5555)).add_modifier(Modifier::BOLD),
    plan_hot: Style::new().fg(rgb(0xFFB86C)).add_modifier(Modifier::BOLD),
    plan_misestimate: Style::new().fg(rgb(0xF1FA8C)).add_modifier(Modifier::UNDERLINED),
    dim: Dim::Blend { toward: rgb(0x16171E), keep: 55 },
};
