//! How a name is written in PostgreSQL SQL so that the server reads it back as that same name.

use super::dialect::Dialect;

/// PostgreSQL's keywords that are not "unreserved" (reserved, column-name and type/function-name
/// keywords): a name equal to one of them must be quoted to be read as a name everywhere.
/// Sorted, lower-case, as in PostgreSQL 17's keyword list.
const QUOTED_KEYWORDS: &[&str] = &[
    "all",
    "analyse",
    "analyze",
    "and",
    "any",
    "array",
    "as",
    "asc",
    "asymmetric",
    "authorization",
    "between",
    "bigint",
    "binary",
    "bit",
    "boolean",
    "both",
    "case",
    "cast",
    "char",
    "character",
    "check",
    "coalesce",
    "collate",
    "collation",
    "column",
    "concurrently",
    "constraint",
    "create",
    "cross",
    "current_catalog",
    "current_date",
    "current_role",
    "current_schema",
    "current_time",
    "current_timestamp",
    "current_user",
    "dec",
    "decimal",
    "default",
    "deferrable",
    "desc",
    "distinct",
    "do",
    "else",
    "end",
    "except",
    "exists",
    "extract",
    "false",
    "fetch",
    "float",
    "for",
    "foreign",
    "freeze",
    "from",
    "full",
    "grant",
    "greatest",
    "group",
    "grouping",
    "having",
    "ilike",
    "in",
    "initially",
    "inner",
    "inout",
    "int",
    "integer",
    "intersect",
    "interval",
    "into",
    "is",
    "isnull",
    "join",
    "json",
    "json_array",
    "json_arrayagg",
    "json_exists",
    "json_object",
    "json_objectagg",
    "json_query",
    "json_scalar",
    "json_serialize",
    "json_table",
    "json_value",
    "lateral",
    "leading",
    "least",
    "left",
    "like",
    "limit",
    "localtime",
    "localtimestamp",
    "merge_action",
    "national",
    "natural",
    "nchar",
    "none",
    "normalize",
    "not",
    "notnull",
    "null",
    "nullif",
    "numeric",
    "offset",
    "on",
    "only",
    "or",
    "order",
    "out",
    "outer",
    "overlaps",
    "overlay",
    "placing",
    "position",
    "precision",
    "primary",
    "real",
    "references",
    "returning",
    "right",
    "row",
    "select",
    "session_user",
    "setof",
    "similar",
    "smallint",
    "some",
    "substring",
    "symmetric",
    "system_user",
    "table",
    "tablesample",
    "then",
    "time",
    "timestamp",
    "to",
    "trailing",
    "treat",
    "trim",
    "true",
    "union",
    "unique",
    "user",
    "using",
    "values",
    "varchar",
    "variadic",
    "verbose",
    "when",
    "where",
    "window",
    "with",
    "xmlattributes",
    "xmlconcat",
    "xmlelement",
    "xmlexists",
    "xmlforest",
    "xmlnamespaces",
    "xmlparse",
    "xmlpi",
    "xmlroot",
    "xmlserialize",
    "xmltable",
];

/// Whether `name` must be written quoted: what PostgreSQL's `quote_ident` quotes. A bare name is
/// folded to lower case, so anything but lower-case ASCII letters, digits and `_` (not starting
/// with a digit) needs quotes, and so does a keyword that is not unreserved.
pub fn needs_quotes(name: &str) -> bool {
    let mut chars = name.chars();
    let plain = chars.next().is_some_and(|c| c.is_ascii_lowercase() || c == '_')
        && chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    !plain || QUOTED_KEYWORDS.binary_search(&name).is_ok()
}

/// `name` as PostgreSQL SQL: bare when that reads back as the same name, else in double quotes
/// with `"` doubled (`Mixed Col` → `"Mixed Col"`). [`Dialect::quote_ident`] of
/// [`Dialect::Postgres`], for the PostgreSQL-only renderers (DDL, plans).
pub fn sql_ident(name: &str) -> String {
    Dialect::Postgres.quote_ident(name)
}

pub mod mysql;

#[cfg(test)]
mod tests;
