use super::super::tests::{Case, check};

/// Every text object with `d`, `c` and `y`, with counts, from inside, on and next to the
/// object, as Vim takes them.
#[test]
fn text_objects_with_operators() {
    const CASES: &[Case] = &[
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "diw",
            "one two\n   four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "daw",
            "one two\n  four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "ciwX<Esc>",
            "one two\n  X four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "caw_<Esc>",
            "one two\n  _four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yiw",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "yaw",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d2iw",
            "one two\n  four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d3iw",
            "one two\n  \nfive six\nseven",
            (1, 1),
            Some(("three four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d2aw",
            "one two\n  \nfive six\nseven",
            (1, 1),
            Some(("three four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "diW",
            "one two\n   four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "daW",
            "one two\n  four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "d3aw",
            "one two\n  six\nseven",
            (1, 2),
            Some(("three four\nfive ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            "diw",
            "one two\nthree four\nfive six\nseven",
            (1, 0),
            Some(("  ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            "daw",
            "one two\n four\nfive six\nseven",
            (1, 0),
            Some(("  three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            "d2iw",
            "one two\n four\nfive six\nseven",
            (1, 0),
            Some(("  three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            "yiw",
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            Some(("  ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            "yaw",
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            Some(("  three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 7),
            "diw",
            "one two\n  threefour\nfive six\nseven",
            (1, 7),
            Some((" ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 7),
            "daw",
            "one two\n  three\nfive six\nseven",
            (1, 6),
            Some((" four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 7),
            "d2aw",
            "one two\n  threesix\nseven",
            (1, 7),
            Some((" four\nfive ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 11),
            "diw",
            "one two\n  three \nfive six\nseven",
            (1, 7),
            Some(("four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 11),
            "daw",
            "one two\n  three\nfive six\nseven",
            (1, 6),
            Some((" four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 11),
            "d2aw",
            "one two\n  three six\nseven",
            (1, 8),
            Some(("four\nfive ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 11),
            "d3aw",
            "one two\n  three\nseven",
            (1, 6),
            Some((" four\nfive six", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 2),
            "daw",
            "one two\n  three four\nfive six\n",
            (3, 0),
            Some(("seven", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 2),
            "diw",
            "one two\n  three four\nfive six\n",
            (3, 0),
            Some(("seven", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 2),
            "yaw",
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            Some(("seven", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 5),
            "diw",
            "foo.(baz) -- qux\nlast_word;",
            (0, 4),
            Some(("bar", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 5),
            "diW",
            " -- qux\nlast_word;",
            (0, 0),
            Some(("foo.bar(baz)", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 5),
            "daW",
            "-- qux\nlast_word;",
            (0, 0),
            Some(("foo.bar(baz) ", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 5),
            "daw",
            "foo.(baz) -- qux\nlast_word;",
            (0, 4),
            Some(("bar", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 5),
            "d3iw",
            "foo.) -- qux\nlast_word;",
            (0, 4),
            Some(("bar(baz", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (1, 9),
            "diw",
            "foo.bar(baz) -- qux\nlast_word",
            (1, 8),
            Some((";", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (1, 9),
            "daw",
            "foo.bar(baz) -- qux\nlast_word",
            (1, 8),
            Some((";", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 4),
            "diw",
            "\u{AC00}\u{B098}  \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            Some(("\u{B2E4}\u{B77C}\u{B9C8}", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 4),
            "daw",
            "\u{AC00}\u{B098} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            Some(("\u{B2E4}\u{B77C}\u{B9C8} ", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 4),
            "ciw\u{C0C8}<Esc>",
            "\u{AC00}\u{B098} \u{C0C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            Some(("\u{B2E4}\u{B77C}\u{B9C8}", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 4),
            "yaw",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            Some(("\u{B2E4}\u{B77C}\u{B9C8} ", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 4),
            "d2aw",
            "\u{AC00}\u{B098}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 1),
            Some((" \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}", false)),
        ),
        ("a\n\nb", (1, 0), "diw", "a\n\nb", (1, 0), None),
        ("a\n\nb", (1, 0), "daw", "a", (0, 0), Some(("\nb", true))),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "di(",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "da(",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "dib",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "dab",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "ci(x<Esc>",
            "SELECT a.id, b.name\nFROM foo(x) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "yi(",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "ya(",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "di)",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "da)",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            "di(",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            "da(",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 17),
            "di(",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 17),
            "da(",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 2),
            "di(",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 2),
            "da(",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 2),
            "ci(x<Esc>",
            "SELECT a.id, b.name\nFROM foo(x) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (2, 20),
            "di(",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON ()\nWHERE a.z IN ('x', 'y')",
            (2, 16),
            Some(("a.x = b.y", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (2, 20),
            "da(",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON \nWHERE a.z IN ('x', 'y')",
            (2, 14),
            Some(("(a.x = b.y)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (2, 20),
            "yi(",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (2, 16),
            Some(("a.x = b.y", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "di{",
            "f(a, [b, {}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            Some(("c", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "da{",
            "f(a, [b, ], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 9),
            Some(("{c}", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "diB",
            "f(a, [b, {}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            Some(("c", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "daB",
            "f(a, [b, ], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 9),
            Some(("{c}", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "di[",
            "f(a, [], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 6),
            Some(("b, {c}", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "da[",
            "f(a, , (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 5),
            Some(("[b, {c}]", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "di(",
            "f()\nx = (1 +\n  (2 * 3)\n)",
            (0, 2),
            Some(("a, [b, {c}], (d)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "da(",
            "f\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "d2i(",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "d2a[",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "d3i(",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "ci[x<Esc>",
            "f(a, [x], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 6),
            Some(("b, {c}", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "di<",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 16),
            "di(",
            "f(a, [b, {c}], ())\nx = (1 +\n  (2 * 3)\n)",
            (0, 16),
            Some(("d", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 16),
            "d2i(",
            "f()\nx = (1 +\n  (2 * 3)\n)",
            (0, 2),
            Some(("a, [b, {c}], (d)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 16),
            "da(",
            "f(a, [b, {c}], )\nx = (1 +\n  (2 * 3)\n)",
            (0, 15),
            Some(("(d)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 16),
            "d2a(",
            "f\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 3),
            "di(",
            "f(a, [b, {c}], (d))\nx = (1 +\n  ()\n)",
            (2, 3),
            Some(("2 * 3", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 3),
            "da(",
            "f(a, [b, {c}], (d))\nx = (1 +\n  \n)",
            (2, 1),
            Some(("(2 * 3)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 3),
            "d2i(",
            "f(a, [b, {c}], (d))\nx = (\n)",
            (1, 4),
            Some(("1 +\n  (2 * 3)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 3),
            "d2a(",
            "f(a, [b, {c}], (d))\nx = ",
            (1, 3),
            Some(("(1 +\n  (2 * 3)\n)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 3),
            "ci(x<Esc>",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (x)\n)",
            (2, 3),
            Some(("2 * 3", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 3),
            "c2i(x<Esc>",
            "f(a, [b, {c}], (d))\nx = (x\n)",
            (1, 5),
            Some(("1 +\n  (2 * 3)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 2),
            "di(",
            "f(a, [b, {c}], (d))\nx = (\n)",
            (1, 4),
            Some(("1 +\n  (2 * 3)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 2),
            "da(",
            "f(a, [b, {c}], (d))\nx = ",
            (1, 3),
            Some(("(1 +\n  (2 * 3)\n)", false)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "di{",
            "begin {\n}\nend",
            (1, 0),
            Some(("    one;\n    two;", true)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "da{",
            "begin \nend",
            (0, 5),
            Some(("{\n    one;\n    two;\n}", false)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "ci{x<Esc>",
            "begin {\n    x\n}\nend",
            (1, 4),
            Some(("    one;\n    two;", true)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "yi{",
            "begin {\n    one;\n    two;\n}\nend",
            (1, 0),
            Some(("    one;\n    two;", true)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "diB",
            "begin {\n}\nend",
            (1, 0),
            Some(("    one;\n    two;", true)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 0),
            "di{",
            "begin {\n}\nend",
            (1, 0),
            Some(("    one;\n    two;", true)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 0),
            "da{",
            "begin \nend",
            (0, 5),
            Some(("{\n    one;\n    two;\n}", false)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (0, 0),
            "di{",
            "begin {\n}\nend",
            (1, 0),
            Some(("    one;\n    two;", true)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (0, 0),
            "da{",
            "begin \nend",
            (0, 5),
            Some(("{\n    one;\n    two;\n}", false)),
        ),
        ("f()", (0, 1), "di(", "f()", (0, 2), None),
        ("f()", (0, 1), "ci(x<Esc>", "f(x)", (0, 2), None),
        ("f()", (0, 1), "da(", "f", (0, 0), Some(("()", false))),
        ("a <b, c> d", (0, 4), "di<", "a <> d", (0, 3), Some(("b, c", false))),
        ("a <b, c> d", (0, 4), "da<", "a  d", (0, 2), Some(("<b, c>", false))),
        ("a <b, c> d", (0, 4), "ci>x<Esc>", "a <x> d", (0, 3), Some(("b, c", false))),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "di\"",
            "say \"\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "da\"",
            "say and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "ci\"x<Esc>",
            "say \"x\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "yi\"",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "ya\"",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "d2i\"",
            "say  and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\"", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            "di\"",
            "say \"\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            "da\"",
            "say and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 13),
            "di\"",
            "say \"\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 13),
            "da\"",
            "say and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 0),
            "di\"",
            "say \"\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 0),
            "da\"",
            "say and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 0),
            "di'",
            "say \"hi there\" and '' ok\n\"a\\\"b\" c `q` d",
            (0, 20),
            Some(("x y", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 0),
            "da'",
            "say \"hi there\" and ok\n\"a\\\"b\" c `q` d",
            (0, 19),
            Some(("'x y' ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 21),
            "di'",
            "say \"hi there\" and '' ok\n\"a\\\"b\" c `q` d",
            (0, 20),
            Some(("x y", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 21),
            "da'",
            "say \"hi there\" and ok\n\"a\\\"b\" c `q` d",
            (0, 19),
            Some(("'x y' ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 21),
            "ci'z<Esc>",
            "say \"hi there\" and 'z' ok\n\"a\\\"b\" c `q` d",
            (0, 20),
            Some(("x y", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 21),
            "di\"",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 21),
            None,
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 26),
            "di'",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 26),
            None,
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 26),
            "da'",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 26),
            None,
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 26),
            "di\"",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 26),
            None,
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 2),
            "di\"",
            "say \"hi there\" and 'x y' ok\n\"\" c `q` d",
            (1, 1),
            Some(("a\\\"b", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 2),
            "da\"",
            "say \"hi there\" and 'x y' ok\nc `q` d",
            (1, 0),
            Some(("\"a\\\"b\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 2),
            "ya\"",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 0),
            Some(("\"a\\\"b\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 9),
            "di`",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `` d",
            (1, 10),
            Some(("q", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 9),
            "da`",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c d",
            (1, 9),
            Some(("`q` ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (1, 9),
            "ci`x<Esc>",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `x` d",
            (1, 10),
            Some(("q", false)),
        ),
        ("x \"\" y", (0, 2), "di\"", "x \"\" y", (0, 3), None),
        ("x \"\" y", (0, 2), "ci\"z<Esc>", "x \"z\" y", (0, 3), None),
        ("x \"\" y", (0, 2), "da\"", "x y", (0, 2), Some(("\"\" ", false))),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "dip",
            "a1\na2\n\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "dap",
            "a1\na2\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "yip",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "yap",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "d2ip",
            "a1\na2\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "d2ap",
            "a1\na2\n\nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n\nc1\n  ", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "cipx<Esc>",
            "a1\na2\n\nx\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "d3ip",
            "a1\na2\n\n  \nd1",
            (3, 1),
            Some(("b1\nb2\nb3\n\n\nc1", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            "dip",
            "a1\na2\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            "dap",
            "a1\na2\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            "d2ip",
            "a1\na2\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (6, 0),
            "dip",
            "a1\na2\n\nb1\nb2\nb3\nc1\n  \nd1",
            (6, 0),
            Some(("\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (6, 0),
            "dap",
            "a1\na2\n\nb1\nb2\nb3\n  \nd1",
            (6, 1),
            Some(("\n\nc1", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (6, 0),
            "yip",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (6, 0),
            Some(("\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (10, 0),
            "dip",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  ",
            (9, 1),
            Some(("d1", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (10, 0),
            "dap",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1",
            (8, 0),
            Some(("  \nd1", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (9, 0),
            "dip",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\nd1",
            (9, 0),
            Some(("  ", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (9, 0),
            "dap",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1",
            (8, 0),
            Some(("  \nd1", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "dap",
            "b1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            Some(("a1\na2\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "d3ap",
            "d1",
            (0, 0),
            Some(("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  ", true)),
        ),
    ];
    check(CASES);
}

/// Text objects in Visual mode set the selection, and grow it when repeated.
#[test]
fn text_objects_in_visual_mode() {
    const CASES: &[Case] = &[
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "viwd",
            "one two\n   four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vawd",
            "one two\n  four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "viwiwd",
            "one two\n  four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vawawd",
            "one two\n  \nfive six\nseven",
            (1, 1),
            Some(("three four", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "v2iwd",
            "one two\n  four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "viWd",
            "one two\n   four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "viwy",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            Some(("three", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vawy",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            Some(("three ", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "vi(d",
            "SELECT a.id, b.name\nFROM foo() a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "va(d",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "vi(y",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            Some(("bar, baz", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 10),
            "vi(a(d",
            "SELECT a.id, b.name\nFROM foo a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            Some(("(bar, baz)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "vi{d",
            "f(a, [b, {}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            Some(("c", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "vi[d",
            "f(a, [], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 6),
            Some(("b, {c}", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "va[d",
            "f(a, , (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 5),
            Some(("[b, {c}]", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 10),
            "vi(d",
            "f()\nx = (1 +\n  (2 * 3)\n)",
            (0, 2),
            Some(("a, [b, {c}], (d)", false)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "vi{d",
            "begin {\n}\nend",
            (1, 0),
            Some(("    one;\n    two;\n", false)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "va{d",
            "begin \nend",
            (0, 5),
            Some(("{\n    one;\n    two;\n}", false)),
        ),
        (
            "begin {\n    one;\n    two;\n}\nend",
            (1, 2),
            "vi{y",
            "begin {\n    one;\n    two;\n}\nend",
            (1, 0),
            Some(("    one;\n    two;\n", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "vi\"d",
            "say \"\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "va\"d",
            "say and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 4),
            Some(("\"hi there\" ", false)),
        ),
        (
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 7),
            "vi\"y",
            "say \"hi there\" and 'x y' ok\n\"a\\\"b\" c `q` d",
            (0, 5),
            Some(("hi there", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vipd",
            "a1\na2\n\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vapd",
            "a1\na2\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vipipd",
            "a1\na2\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vapapd",
            "a1\na2\n\nd1",
            (3, 0),
            Some(("b1\nb2\nb3\n\n\nc1\n  ", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "Vipd",
            "a1\na2\n\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vipy",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vjipd",
            "a1\na2\n\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            Some(("1\nb2\nb", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (3, 1),
            "vjapd",
            "a1\na2\n\nbc1\n  \nd1",
            (3, 1),
            Some(("1\nb2\nb3\n\n\n", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (5, 1),
            "vkipd",
            "a1\na2\n\n\n\n\nc1\n  \nd1",
            (3, 0),
            Some(("b1\nb2\nb3", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (5, 1),
            "vkapd",
            "a1\na2\n\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb2\nb3", false)),
        ),
    ];
    check(CASES);
}
