// MySQL statements and what the classifier must say of them, shared by the unit tests
// (`tests.rs`) and the test that runs them on MySQL servers (`tests/mysql_classify.rs`).
//
// The expectation is the class, then the danger (with how a WHERE lets every row through:
// `:missing`, `:always`, `:nocol`), then the flags that are set, in this order: `writes`,
// `plan`/`analyze`, `rw` (asks for read-write), `commit` (commits the open transaction), `code`
// (runs code the text does not show), `udf` (calls a function that is not a built-in), `ro` (a
// read-only policy lets it run). The objects are those the server test creates (`zz_cls_*`).
//
// The server test runs every statement whose class is `read`, `write` or `ddl` with the
// session's `transaction_read_only` on: a read must not fail as a write (error 1792), and a
// write or a DDL statement must, unless its expectation ends with `srvok`: the server lets it
// through, and only the classifier stops it. One that ends with `norun` is not sent (it needs
// what the test does not set up). Neither word is part of what the classifier says.

const CORPUS: &[(&str, &str)] = &[
    // Plain queries.
    ("SELECT 1", "read ro"),
    ("select 1", "read ro"),
    ("SELECT * FROM zz_cls_t", "read ro"),
    ("SELECT id, a FROM zz_cls_t WHERE a > 1 ORDER BY id LIMIT 10", "read ro"),
    ("SELECT * FROM zz_cls_t LIMIT 2, 3", "read ro"),
    ("SELECT * FROM zz_cls_t LIMIT 3 OFFSET 2", "read ro"),
    ("SELECT DISTINCT a FROM zz_cls_t", "read ro"),
    ("SELECT COUNT(*) FROM zz_cls_t", "read ro"),
    ("SELECT a, COUNT(*) FROM zz_cls_t GROUP BY a WITH ROLLUP", "read ro"),
    ("SELECT a, COUNT(*) AS n FROM zz_cls_t GROUP BY a HAVING n > 1", "read ro"),
    ("SELECT `id`, `a` FROM `zz_cls_t` AS `t`", "read ro"),
    ("SELECT t.id FROM zz_cls_t t JOIN zz_cls_u u ON u.t_id = t.id", "read ro"),
    ("SELECT * FROM zz_cls_t LEFT JOIN zz_cls_u ON zz_cls_u.t_id = zz_cls_t.id", "read ro"),
    ("SELECT * FROM zz_cls_t RIGHT OUTER JOIN zz_cls_u USING (id)", "read ro"),
    ("SELECT * FROM zz_cls_t NATURAL JOIN zz_cls_u", "read ro"),
    ("SELECT * FROM zz_cls_t CROSS JOIN zz_cls_u", "read ro"),
    ("SELECT STRAIGHT_JOIN * FROM zz_cls_t, zz_cls_u", "read ro"),
    ("SELECT * FROM zz_cls_t t1 STRAIGHT_JOIN zz_cls_u u1 ON u1.t_id = t1.id", "read ro"),
    ("SELECT HIGH_PRIORITY SQL_NO_CACHE SQL_BIG_RESULT a FROM zz_cls_t", "read ro"),
    ("SELECT SQL_CALC_FOUND_ROWS * FROM zz_cls_t LIMIT 1", "read ro"),
    ("SELECT * FROM zz_cls_t FORCE INDEX (PRIMARY) WHERE id = 1", "read ro"),
    ("SELECT * FROM zz_cls_t USE INDEX (zz_cls_a) WHERE a = 1", "read ro"),
    ("SELECT * FROM zz_cls_t IGNORE KEY (zz_cls_a)", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE id IN (SELECT t_id FROM zz_cls_u)", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE EXISTS (SELECT 1 FROM zz_cls_u WHERE zz_cls_u.t_id = zz_cls_t.id)", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE id = ANY (SELECT t_id FROM zz_cls_u)", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE a > ALL (SELECT t_id FROM zz_cls_u)", "read ro"),
    ("SELECT (SELECT MAX(id) FROM zz_cls_u) AS m", "read ro"),
    ("SELECT * FROM (SELECT id FROM zz_cls_t) AS d", "read ro"),
    ("SELECT * FROM (SELECT id, a FROM zz_cls_t) AS d (x, y)", "read ro"),
    ("SELECT * FROM zz_cls_t, LATERAL (SELECT zz_cls_t.id + 1 AS n) AS l", "read ro"),
    ("SELECT a FROM zz_cls_t UNION SELECT t_id FROM zz_cls_u", "read ro"),
    ("SELECT a FROM zz_cls_t UNION ALL SELECT t_id FROM zz_cls_u ORDER BY 1", "read ro"),
    ("SELECT a FROM zz_cls_t UNION DISTINCT SELECT t_id FROM zz_cls_u", "read ro"),
    ("SELECT a FROM zz_cls_t EXCEPT SELECT t_id FROM zz_cls_u", "read ro"),
    ("SELECT a FROM zz_cls_t INTERSECT SELECT t_id FROM zz_cls_u", "read ro"),
    ("(SELECT 1) UNION (SELECT 2) ORDER BY 1", "read ro"),
    ("(SELECT id FROM zz_cls_t ORDER BY id LIMIT 1)", "read ro"),
    ("((SELECT 1))", "read ro"),
    ("SELECT 1 FROM DUAL", "read ro"),
    ("SELECT 1 + 1, 7 DIV 2, 7 MOD 2, 7 % 2, 1 XOR 0, NOT 1, !0, ~1, 1 << 2, 6 >> 1, 5 & 3, 5 | 3, 5 ^ 3", "read ro"),
    ("SELECT 1 = 1, 1 <=> NULL, 1 != 2, 1 <> 2, 1 <= 2, 2 >= 1, 1 IS TRUE, NULL IS NULL, 1 IS NOT NULL", "read ro"),
    ("SELECT 1 BETWEEN 0 AND 2, 'a' LIKE 'a%', 'a' NOT LIKE 'b', 'a' REGEXP 'a', 'a' RLIKE 'a', 'a' SOUNDS LIKE 'a'", "read ro"),
    ("SELECT 1 IN (1, 2), 3 NOT IN (1, 2), 1 && 1, 0 || 1", "read ro"),
    ("SELECT CASE WHEN a > 1 THEN 'x' ELSE 'y' END FROM zz_cls_t", "read ro"),
    ("SELECT CASE a WHEN 1 THEN 'one' END FROM zz_cls_t", "read ro"),
    ("SELECT IF(a > 1, 1, 0), IFNULL(b, ''), NULLIF(a, 1), COALESCE(b, 'x') FROM zz_cls_t", "read ro"),
    ("SELECT CAST(a AS CHAR), CAST(a AS DECIMAL(10, 2)), CAST('1' AS SIGNED), CAST(a AS UNSIGNED) FROM zz_cls_t", "read ro"),
    ("SELECT CONVERT(b USING utf8mb4), CONVERT(a, CHAR(10)), BINARY b FROM zz_cls_t", "read ro"),
    ("SELECT CONCAT(b, 'x'), CONCAT_WS('-', a, b), LENGTH(b), CHAR_LENGTH(b), UPPER(b), LOWER(b) FROM zz_cls_t", "read ro"),
    ("SELECT SUBSTRING(b, 1, 2), SUBSTRING(b FROM 1 FOR 2), TRIM(BOTH 'x' FROM b), LEFT(b, 1), RIGHT(b, 1) FROM zz_cls_t", "read ro"),
    ("SELECT REPLACE(b, 'a', 'b'), INSERT(b, 1, 1, 'z'), REPEAT('a', 3), REVERSE(b), LPAD(b, 5, '*') FROM zz_cls_t", "read ro"),
    ("SELECT LOCATE('a', b), INSTR(b, 'a'), POSITION('a' IN b), FIELD(a, 1, 2), FIND_IN_SET('a', b) FROM zz_cls_t", "read ro"),
    ("SELECT GROUP_CONCAT(b ORDER BY id SEPARATOR ',') FROM zz_cls_t", "read ro"),
    ("SELECT ABS(-1), ROUND(1.5), FLOOR(1.5), CEIL(1.2), MOD(7, 2), POW(2, 3), SQRT(4), PI(), TRUNCATE(1.55, 1)", "read ro"),
    ("SELECT NOW(), CURDATE(), CURTIME(), CURRENT_TIMESTAMP, CURRENT_DATE, LOCALTIME, UTC_TIMESTAMP(), UNIX_TIMESTAMP()", "read ro"),
    ("SELECT DATE_ADD(d, INTERVAL 1 DAY), d + INTERVAL 1 MONTH, DATEDIFF(d, '2020-01-01'), DATE_FORMAT(d, '%Y') FROM zz_cls_t", "read ro"),
    ("SELECT EXTRACT(YEAR FROM d), YEAR(d), MONTH(d), DAY(d), TIMESTAMPDIFF(DAY, d, NOW()) FROM zz_cls_t", "read ro"),
    ("SELECT JSON_EXTRACT(j, '$.a'), j->'$.a', j->>'$.a', JSON_OBJECT('a', 1), JSON_ARRAY(1, 2) FROM zz_cls_t", "read ro"),
    ("SELECT JSON_ARRAYAGG(id), JSON_OBJECTAGG(id, a) FROM zz_cls_t", "read ro"),
    ("SELECT * FROM JSON_TABLE('[1, 2]', '$[*]' COLUMNS (x INT PATH '$', n FOR ORDINALITY)) AS jt", "read ro"),
    ("SELECT * FROM JSON_TABLE('[{\"a\": \"x\"}]', '$[*]' COLUMNS (a VARCHAR(10) PATH '$.a', NESTED PATH '$' COLUMNS (b DECIMAL(5, 2) PATH '$.b'))) AS jt", "read ro"),
    ("SELECT ROW_NUMBER() OVER (ORDER BY id), RANK() OVER w, LAG(a) OVER w FROM zz_cls_t WINDOW w AS (PARTITION BY a ORDER BY id)", "read ro"),
    ("SELECT SUM(a) OVER (PARTITION BY b ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM zz_cls_t", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE MATCH (b) AGAINST ('x' IN BOOLEAN MODE)", "read ro norun"),
    ("SELECT MD5('a'), SHA2('a', 256), CRC32('a'), HEX('a'), UNHEX('41'), TO_BASE64('a')", "read ro"),
    ("SELECT UUID_TO_BIN('6ccd780c-baba-1026-9564-5b8c656024db'), INET_ATON('10.0.0.1'), BIN(5), CONV(10, 10, 2)", "read ro"),
    ("SELECT DATABASE(), SCHEMA(), USER(), CURRENT_USER(), CURRENT_USER, VERSION(), CONNECTION_ID()", "read ro"),
    ("SELECT ST_AsText(POINT(1, 2)), ST_Distance(POINT(0, 0), POINT(1, 1))", "read ro"),
    ("SELECT REGEXP_REPLACE('abc', 'b', 'x'), REGEXP_LIKE('abc', 'b'), REGEXP_SUBSTR('abc', 'b')", "read ro"),
    ("SELECT ANY_VALUE(b), BIT_AND(a), STDDEV(a), VARIANCE(a) FROM zz_cls_t", "read ro"),
    ("SELECT SLEEP(0)", "read ro"),
    ("SELECT BENCHMARK(1, 1)", "read ro"),
    ("SELECT RAND(), UUID(), UUID_SHORT(), SYSDATE(), LAST_INSERT_ID(), FOUND_ROWS(), ROW_COUNT()", "read ro"),
    ("SELECT IS_FREE_LOCK('zz_cls'), IS_USED_LOCK('zz_cls')", "read ro"),
    ("SELECT X'41', x'42', 0x43, B'1', b'0', 0b1, N'n', _utf8mb4'u', _latin1 'l'", "read ro"),
    ("SELECT 'it''s', 'it\\'s', \"dq\", 'a' 'b', '\\\\'", "read ro"),
    ("SELECT 1e5, .5, 5., 1.5e-3, -1, +1", "read ro"),
    ("SELECT TRUE, FALSE, NULL, 1 IS UNKNOWN", "read ro"),
    ("SELECT @x, @@version, @@session.sql_mode, @@global.max_connections, @`x`, @'y', @\"z\"", "read ro"),
    ("SELECT @x := 1", "read ro"),
    ("SELECT id FROM zz_cls_t WHERE id = @x", "read ro"),
    ("SELECT {d '2024-01-01'}, {t '10:00:00'}", "read ro"),
    ("SELECT * FROM zz_cls_t PARTITION (p0)", "read ro norun"),
    // Comments and hints everywhere.
    ("SELECT /* a comment */ 1", "read ro"),
    ("SELECT 1 -- a comment", "read ro"),
    ("SELECT 1 # a comment", "read ro"),
    ("-- leading\nSELECT 1", "read ro"),
    ("# leading\nSELECT 1", "read ro"),
    ("/* leading */ SELECT 1", "read ro"),
    ("SELECT 1 /* DELETE FROM zz_cls_t */", "read ro"),
    ("SELECT 1 -- ; DELETE FROM zz_cls_t", "read ro"),
    ("SELECT 1 # ; DROP TABLE zz_cls_t", "read ro"),
    ("SELECT 1--1", "read ro"),
    ("SELECT 1 --\n, 2", "read ro"),
    ("SELECT /*+ MAX_EXECUTION_TIME(1000) */ * FROM zz_cls_t", "read ro"),
    ("SELECT /*+ SET_VAR(sort_buffer_size = 16M) BKA(t) */ * FROM zz_cls_t t", "read ro"),
    ("SELECT /*+ SET_VAR(sql_mode = 'ANSI_QUOTES') */ 1", "read setting"),
    ("SELECT /*+ NO_INDEX(zz_cls_t) */ 1 FROM zz_cls_t", "read ro"),
    ("SELECT 'a /* b' AS s, \"c -- d\" AS t, `e # f` FROM (SELECT 1 AS `e # f`) AS x", "read ro"),
    ("SELECT ';' AS semi, 'x;DROP TABLE zz_cls_t' AS s", "read ro"),
    // Executable comments are never read.
    ("SELECT /*! 1 */", "unknown exec-comment"),
    ("SELECT 1 /*!80000 , 2 */", "unknown exec-comment"),
    ("SELECT 1 /*!99999 , 2 */", "unknown exec-comment"),
    ("SELECT 1 /*!090000 , 2 */", "unknown exec-comment"),
    ("/*!40101 SET NAMES utf8mb4 */", "unknown exec-comment"),
    ("SELECT 1 /*! ; DELETE FROM zz_cls_t */", "unknown exec-comment"),
    ("/*!50000 DELETE FROM zz_cls_t */", "unknown exec-comment"),
    ("SELECT /*!50000 SQL_NO_CACHE */ 1", "unknown exec-comment"),
    ("SELECT 1 /*M! , 2 */", "unknown exec-comment"),
    ("SELECT 1 /*M!100000 , 2 */", "unknown exec-comment"),
    ("CREATE TABLE zz_x (a INT) /*!50100 PARTITION BY HASH (a) */", "unknown exec-comment"),
    // Texts the server would read otherwise, or forms not known.
    ("SELECT 'unterminated", "unknown unrecognized"),
    ("SELECT \"unterminated", "unknown unrecognized"),
    ("SELECT `unterminated", "unknown unrecognized"),
    ("SELECT 1 /* unterminated", "unknown unrecognized"),
    ("SELECT 'a\\'", "unknown unrecognized"),
    ("SELECT ?", "unknown unrecognized"),
    ("SELECT (1", "unknown unrecognized"),
    ("SELECT 1)", "unknown unrecognized"),
    ("SELECT 1\\G", "unknown unrecognized"),
    ("SELECT 1 \\g", "unknown unrecognized"),
    ("SELECT 1 \\\nFROM DUAL", "unknown unrecognized"),
    ("DELIMITER $$", "unknown unrecognized"),
    ("SELECT 1\u{1}", "unknown unrecognized"),
    ("SELEC 1", "unknown unrecognized"),
    ("`SELECT` 1", "unknown unrecognized"),
    ("BEGIN NOT ATOMIC SELECT 1; END", "unknown unrecognized"),
    ("DECLARE x INT", "unknown unrecognized"),
    ("IF 1 THEN SELECT 1; END IF", "unknown unrecognized"),
    ("SELECT * FROM zz_cls_t WHERE id IN (DELETE FROM zz_cls_t)", "unknown unrecognized"),
    ("SELECT (UPDATE zz_cls_t SET a = 1)", "unknown unrecognized"),
    ("SELECT 1 FROM zz_cls_t WHERE 1 = (INSERT INTO zz_cls_t VALUES (9))", "unknown unrecognized"),
    ("SET @x = (DELETE FROM zz_cls_t)", "unknown unrecognized"),
    ("SET @x := (SELECT 1 FROM zz_cls_t UNION DELETE FROM zz_cls_t)", "unknown unrecognized"),
    ("SHOW TABLES; DROP TABLE zz_cls_t", "ddl drop commit"),
    ("SELECT 1 INTO zz_var", "unknown unrecognized"),
    ("SELECT 1 INTO @@session.sql_mode", "unknown unrecognized"),
    ("SELECT 1 INTO", "unknown unrecognized"),
    ("", "unknown"),
    ("-- only a comment", "unknown"),
    (";", "unknown"),
    // Several statements: the worst.
    ("SELECT 1; SELECT 2", "read ro"),
    ("SELECT 1;", "read ro"),
    ("SELECT 1; DELETE FROM zz_cls_t", "write delete-all:missing writes"),
    ("SELECT 1; SET GLOBAL max_connections = 100", "maint server-command commit"),
    // Locking reads inside other statements.
    ("SET @x = (SELECT id FROM zz_cls_t WHERE id = 2 FOR SHARE)", "write srvok"),
    ("SET @x := (SELECT id FROM zz_cls_t WHERE id = 1 LOCK IN SHARE MODE)", "write srvok"),
    ("SET @x = (SELECT id FROM zz_cls_t WHERE id = 1 FOR UPDATE)", "write"),
    ("SHOW TABLES WHERE (SELECT 1 FROM zz_cls_t WHERE id = 2 FOR SHARE)", "write srvok"),
    ("DO (SELECT 1 FROM zz_cls_t WHERE id = 1 FOR SHARE)", "write srvok"),
    // Read in another sql mode, the text does something else.
    ("SELECT 'a\\' , GET_LOCK(0x78, 0) #'", "read server-action"),
    ("SELECT 1 AS \"a\\\", GET_LOCK(0x78, 0) #\"", "unknown server-action"),
    ("SELECT 'a\\' , 1 INTO OUTFILE '/tmp/zz' #'", "write file-access srvok"),
    ("SELECT 'it\\'s'", "read ro"),
    ("SELECT \"x\" FROM zz_cls_t", "read ro"),
    // Odd SET texts.
    ("SET CHARACTER", "unknown unrecognized"),
    ("SET x = 1, CHARACTER", "unknown unrecognized"),
    ("SET @\u{e9} x = 1", "unknown unrecognized"),
    // TABLE and VALUES.
    ("TABLE zz_cls_t", "read ro"),
    ("TABLE zz_cls_t ORDER BY id LIMIT 1", "read ro"),
    ("TABLE zz_cls_t UNION TABLE zz_cls_t", "read ro"),
    ("VALUES ROW(1, 2), ROW(3, 4)", "read ro"),
    ("VALUES ROW(1, 2) ORDER BY column_0", "read ro"),
    ("SELECT * FROM (VALUES ROW(1, 2)) AS v (a, b)", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE id IN (TABLE zz_cls_u)", "read ro norun"),
    // WITH.
    ("WITH c AS (SELECT 1 AS n) SELECT * FROM c", "read ro"),
    ("WITH c (n) AS (SELECT 1) SELECT n FROM c", "read ro"),
    ("WITH RECURSIVE c (n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM c WHERE n < 5) SELECT * FROM c", "read ro"),
    ("WITH a AS (SELECT 1 AS x), b AS (SELECT x + 1 AS y FROM a) SELECT * FROM a, b", "read ro"),
    ("WITH c AS (SELECT id FROM zz_cls_t) TABLE c", "read ro"),
    ("WITH c AS (SELECT 1) (SELECT * FROM c)", "read ro"),
    ("SELECT * FROM (WITH c AS (SELECT 1 AS n) SELECT n FROM c) AS d", "read ro"),
    ("WITH c AS (SELECT id FROM zz_cls_u) DELETE FROM zz_cls_t WHERE id IN (SELECT id FROM c)", "write writes"),
    ("WITH c AS (SELECT id FROM zz_cls_u) DELETE FROM zz_cls_t", "write delete-all:missing writes"),
    ("WITH c AS (SELECT 1 AS n) UPDATE zz_cls_t, c SET a = c.n WHERE id = 1", "write writes"),
    ("WITH c AS (SELECT 1 AS n) UPDATE zz_cls_t SET a = (SELECT n FROM c)", "write update-all:missing writes"),
    ("WITH c AS (SELECT 1) INSERT INTO zz_cls_t SELECT * FROM c", "unknown unrecognized"),
    ("WITH c AS (DELETE FROM zz_cls_t) SELECT 1", "unknown unrecognized"),
    ("WITH c AS (SELECT 1) SELECT * FROM c FOR UPDATE", "write srvok"),
    ("WITH SELECT 1", "unknown unrecognized"),
    ("WITH c AS (SELECT 1)", "unknown unrecognized"),
    ("WITH c AS SELECT 1", "unknown unrecognized"),
    // Locking reads.
    ("SELECT * FROM zz_cls_t WHERE id = 1 FOR UPDATE", "write"),
    ("SELECT * FROM zz_cls_t FOR UPDATE NOWAIT", "write"),
    ("SELECT * FROM zz_cls_t FOR UPDATE SKIP LOCKED", "write"),
    ("SELECT * FROM zz_cls_t t FOR UPDATE OF t", "write"),
    ("SELECT * FROM zz_cls_t FOR SHARE", "write srvok"),
    ("SELECT * FROM zz_cls_t LOCK IN SHARE MODE", "write srvok"),
    ("SELECT * FROM zz_cls_t LOCK IN `SHARE` MODE", "write norun"),
    ("SELECT * FROM zz_cls_t FOR `UPDATE`", "write norun"),
    ("SELECT * FROM zz_cls_t WHERE id IN (SELECT t_id FROM zz_cls_u FOR UPDATE)", "write"),
    ("(SELECT * FROM zz_cls_t FOR UPDATE)", "write"),
    ("TABLE zz_cls_t FOR UPDATE", "write norun"),
    // INTO.
    ("SELECT id INTO @x FROM zz_cls_t LIMIT 1", "session ro"),
    ("SELECT id, a INTO @x, @y FROM zz_cls_t LIMIT 1", "session ro"),
    ("SELECT id FROM zz_cls_t LIMIT 1 INTO @x", "session ro"),
    ("SELECT 1 INTO @x FOR UPDATE", "write srvok"),
    ("SELECT * FROM zz_cls_t INTO OUTFILE '/tmp/zz_cls_out'", "write file-access srvok"),
    ("SELECT * INTO OUTFILE '/tmp/zz_cls_out' FROM zz_cls_t", "write file-access srvok"),
    ("SELECT b FROM zz_cls_t LIMIT 1 INTO DUMPFILE '/tmp/zz_cls_dump'", "write file-access srvok"),
    ("TABLE zz_cls_t INTO OUTFILE '/tmp/zz_cls_out'", "write file-access srvok"),
    ("SELECT 1 INTO @a, zz_local", "unknown unrecognized"),
    // Server files and actions.
    ("SELECT LOAD_FILE('/etc/hostname')", "read server-file"),
    ("SELECT load_file('/etc/hostname')", "read server-file"),
    ("SELECT `LOAD_FILE`('/etc/hostname')", "read server-file"),
    ("SELECT LOAD_FILE ('/etc/hostname')", "read server-file"),
    ("SELECT LOAD_FILE/**/('/etc/hostname')", "read server-file"),
    ("SELECT * FROM zz_cls_t WHERE b = LOAD_FILE('/etc/hostname')", "read server-file"),
    ("SELECT * FROM zz_cls_t t JOIN zz_cls_u u ON LOAD_FILE('/x') = u.id", "read server-file"),
    ("SELECT GET_LOCK('zz_cls', 0)", "read server-action"),
    ("SELECT RELEASE_LOCK('zz_cls')", "read server-action"),
    ("SELECT RELEASE_ALL_LOCKS()", "read server-action"),
    ("DO GET_LOCK('zz_cls', 0)", "read server-action"),
    ("SHOW TABLES WHERE GET_LOCK('zz_cls', 0)", "read server-action"),
    ("SET @x = LOAD_FILE('/etc/hostname')", "session server-file"),
    ("INSERT INTO zz_cls_t (id, b) VALUES (9, LOAD_FILE('/etc/hostname'))", "write server-file writes"),
    // Functions that are not built-ins.
    ("SELECT zz_cls_f()", "read code udf"),
    ("SELECT zz_classify.zz_cls_f()", "read code udf"),
    ("SELECT `zz_classify`.`zz_cls_f`()", "read code udf"),
    ("SELECT sys_exec('id')", "read code udf"),
    ("SELECT `sys_exec`('id')", "read code udf"),
    ("SELECT * FROM zz_cls_t WHERE zz_cls_f() = a", "read code udf"),
    ("SELECT a DIV (2) FROM zz_cls_t", "read ro"),
    ("DO 1 + 1", "read ro"),
    ("DO SLEEP(0)", "read ro"),
    ("DO zz_cls_f()", "proc procedural code udf"),
    ("DO zz_classify.zz_cls_f()", "proc procedural code udf"),
    ("SELECT VECTOR_DIM(STRING_TO_VECTOR('[1, 2]'))", "read ro norun"),
    ("SELECT 3 MEMBER OF ('[1, 3]')", "read ro"),
    ("SELECT * FROM (SELECT 1) d (a)", "read ro"),
    ("SELECT CONVERT('2020-01-01', DATETIME(6)), CONVERT('a', NCHAR(2))", "read ro"),
    ("SELECT JSON_VALUE('{\"a\": 1}', '$.a' RETURNING DECIMAL(4, 2))", "read ro"),
    ("SELECT text('x')", "read code udf"),
    ("SELECT hash(1)", "read code udf"),
    // SHOW, DESCRIBE, HELP and the like.
    ("SHOW TABLES", "read ro"),
    ("SHOW FULL TABLES FROM zz_classify LIKE 'zz%'", "read ro"),
    ("SHOW DATABASES", "read ro"),
    ("SHOW COLUMNS FROM zz_cls_t", "read ro"),
    ("SHOW FULL COLUMNS FROM zz_cls_t WHERE Field = 'id'", "read ro"),
    ("SHOW INDEX FROM zz_cls_t", "read ro"),
    ("SHOW CREATE TABLE zz_cls_t", "read ro"),
    ("SHOW CREATE VIEW zz_cls_v", "read ro"),
    ("SHOW CREATE DATABASE zz_classify", "read ro"),
    ("SHOW CREATE PROCEDURE zz_cls_p", "read ro"),
    ("SHOW CREATE USER CURRENT_USER", "read ro"),
    ("SHOW TABLE STATUS", "read ro"),
    ("SHOW VARIABLES LIKE 'sql_mode'", "read ro"),
    ("SHOW SESSION VARIABLES WHERE Variable_name = 'autocommit'", "read ro"),
    ("SHOW GLOBAL STATUS LIKE 'Uptime'", "read ro"),
    ("SHOW PROCESSLIST", "read ro"),
    ("SHOW FULL PROCESSLIST", "read ro"),
    ("SHOW GRANTS", "read ro"),
    ("SHOW GRANTS FOR CURRENT_USER", "read ro"),
    ("SHOW PRIVILEGES", "read ro"),
    ("SHOW WARNINGS", "read ro"),
    ("SHOW ERRORS", "read ro"),
    ("SHOW COUNT(*) WARNINGS", "read ro"),
    ("SHOW ENGINES", "read ro"),
    ("SHOW ENGINE INNODB STATUS", "read ro"),
    ("SHOW CHARACTER SET", "read ro"),
    ("SHOW COLLATION LIKE 'utf8mb4_bin'", "read ro"),
    ("SHOW TRIGGERS", "read ro"),
    ("SHOW PROCEDURE STATUS WHERE Db = 'zz_classify'", "read ro"),
    ("SHOW FUNCTION STATUS", "read ro"),
    ("SHOW EVENTS", "read ro"),
    ("SHOW OPEN TABLES", "read ro"),
    ("SHOW PLUGINS", "read ro"),
    ("SHOW BINARY LOGS", "read ro norun"),
    ("SHOW BINLOG EVENTS", "read ro norun"),
    ("SHOW REPLICA STATUS", "read ro norun"),
    ("SHOW PROFILES", "read ro"),
    ("SHOW STATUS", "read ro"),
    ("DESCRIBE zz_cls_t", "read ro"),
    ("DESC zz_cls_t", "read ro"),
    ("DESCRIBE zz_cls_t id", "read ro"),
    ("DESC zz_cls_t 'i%'", "read ro"),
    ("EXPLAIN zz_cls_t", "read ro"),
    ("HELP 'contents'", "read ro"),
    ("XA RECOVER", "read ro"),
    ("GET DIAGNOSTICS @n = NUMBER", "read ro"),
    ("GET DIAGNOSTICS CONDITION 1 @c = MYSQL_ERRNO", "read ro"),
    ("SIGNAL SQLSTATE '45000'", "read ro norun"),
    // EXPLAIN.
    ("EXPLAIN SELECT * FROM zz_cls_t", "read plan ro"),
    ("EXPLAIN FORMAT=JSON SELECT * FROM zz_cls_t", "read plan ro"),
    ("EXPLAIN FORMAT = TREE SELECT * FROM zz_cls_t", "read plan ro"),
    ("EXPLAIN FORMAT='JSON' SELECT 1", "read plan ro"),
    ("DESCRIBE SELECT * FROM zz_cls_t", "read plan ro"),
    ("DESC FORMAT=TRADITIONAL SELECT 1", "read plan ro"),
    ("EXPLAIN TABLE zz_cls_t", "read plan ro"),
    ("EXPLAIN WITH c AS (SELECT 1) SELECT * FROM c", "read plan ro"),
    ("EXPLAIN (SELECT 1) UNION (SELECT 2)", "read plan ro"),
    ("EXPLAIN SELECT * FROM zz_cls_t FOR UPDATE", "read plan ro"),
    ("EXPLAIN SELECT * FROM zz_cls_t INTO OUTFILE '/tmp/zz_cls_out'", "write file-access plan srvok"),
    ("EXPLAIN DELETE FROM zz_cls_t", "write plan"),
    ("EXPLAIN UPDATE zz_cls_t SET a = 1", "write plan"),
    ("EXPLAIN INSERT INTO zz_cls_t VALUES (9, 9, 'x', NULL, NULL)", "write plan"),
    ("EXPLAIN REPLACE INTO zz_cls_t VALUES (9, 9, 'x', NULL, NULL)", "write plan"),
    ("EXPLAIN FORMAT=JSON DELETE FROM zz_cls_t WHERE id = 1", "write plan"),
    ("EXPLAIN ANALYZE SELECT * FROM zz_cls_t", "read analyze ro"),
    ("EXPLAIN ANALYZE FORMAT=TREE SELECT * FROM zz_cls_t", "read analyze ro"),
    ("EXPLAIN FORMAT=TREE ANALYZE SELECT 1", "read analyze ro norun"),
    ("EXPLAIN ANALYZE UPDATE zz_cls_t SET a = 1 WHERE id = 1", "write writes analyze"),
    ("EXPLAIN ANALYZE DELETE FROM zz_cls_t", "write delete-all:missing writes analyze"),
    ("EXPLAIN ANALYZE SELECT * FROM zz_cls_t FOR UPDATE", "write analyze srvok"),
    ("EXPLAIN ANALYZE SELECT GET_LOCK('zz_cls', 0)", "read server-action analyze"),
    ("EXPLAIN SELECT zz_cls_f()", "read plan code udf"),
    ("EXPLAIN FOR CONNECTION 1", "read ro norun"),
    ("EXPLAIN FORMAT=JSON INTO @p SELECT 1", "session plan ro norun"),
    ("EXPLAIN SELEC 1", "unknown unrecognized"),
    ("EXPLAIN", "unknown unrecognized"),
    ("EXPLAIN ANALYZE zz_cls_t", "unknown unrecognized"),
    ("EXPLAIN /*!80000 ANALYZE */ DELETE FROM zz_cls_t", "unknown exec-comment"),
    // INSERT and REPLACE.
    ("INSERT INTO zz_cls_t VALUES (9, 9, 'x', NULL, NULL)", "write writes"),
    ("INSERT INTO zz_cls_t (id, a) VALUES (9, 9), (10, 10)", "write writes"),
    ("INSERT zz_cls_t (id) VALUES (9)", "write writes"),
    ("INSERT INTO zz_cls_t SET id = 9, a = 9", "write writes"),
    ("INSERT IGNORE INTO zz_cls_t (id) VALUES (1)", "write writes"),
    ("INSERT LOW_PRIORITY INTO zz_cls_t (id) VALUES (9)", "write writes"),
    ("INSERT INTO zz_cls_t (id, a) VALUES (1, 1) ON DUPLICATE KEY UPDATE a = VALUES(a) + 1", "write writes"),
    ("INSERT INTO zz_cls_t (id, a) VALUES (1, 1) AS n ON DUPLICATE KEY UPDATE a = n.a", "write writes"),
    ("INSERT INTO zz_cls_t (id) SELECT id + 100 FROM zz_cls_u", "write writes"),
    ("INSERT INTO zz_cls_t (id) TABLE zz_cls_u", "write writes norun"),
    ("INSERT INTO zz_cls_t (id) VALUES (zz_cls_f())", "write writes code udf"),
    ("REPLACE INTO zz_cls_t VALUES (1, 1, 'r', NULL, NULL)", "write writes"),
    ("REPLACE zz_cls_t (id) VALUES (1)", "write writes"),
    ("REPLACE INTO zz_cls_t (id) SELECT t_id FROM zz_cls_u", "write writes"),
    ("INSERT /*+ SET_VAR(foreign_key_checks = 0) */ INTO zz_cls_t (id) VALUES (9)", "write setting writes"),
    // UPDATE.
    ("UPDATE zz_cls_t SET a = 1 WHERE id = 1", "write writes"),
    ("UPDATE zz_cls_t SET a = 1", "write update-all:missing writes"),
    ("UPDATE zz_cls_t SET a = 1 LIMIT 1", "write update-all:missing writes"),
    ("UPDATE zz_cls_t SET a = 1 ORDER BY id LIMIT 1", "write update-all:missing writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE 1 = 1", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE TRUE", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE 1", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE NOT FALSE", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE id = id", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE id <=> id", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE (id = 5 OR 1 = 1)", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE id = 5 || TRUE", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE 1 = 1 AND TRUE", "write update-all:always writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE 1 = 1 AND id = 5", "write writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE 2 > 1", "write update-all:nocol writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE @x = 1", "write update-all:nocol writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE NOW() > '2000-01-01'", "write update-all:nocol writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE CURRENT_DATE > '2000-01-01' - INTERVAL 1 DAY", "write update-all:nocol writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE 'a' = 'A' COLLATE utf8mb4_bin", "write update-all:nocol writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE _utf8mb4'x' = 'x'", "write update-all:nocol writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE d > NOW() - INTERVAL 1 DAY", "write writes"),
    ("UPDATE zz_cls_t SET a = 1 WHERE `a` IS NULL", "write writes"),
    ("UPDATE zz_cls_t SET a = (SELECT MAX(t_id) FROM zz_cls_u WHERE t_id > 0)", "write update-all:missing writes"),
    ("UPDATE LOW_PRIORITY IGNORE zz_cls_t SET a = 1 WHERE id = 1", "write writes"),
    ("UPDATE zz_cls_t t JOIN zz_cls_u u ON u.t_id = t.id SET t.a = 1", "write update-all:missing writes"),
    ("UPDATE zz_cls_t t JOIN zz_cls_u u ON u.t_id = t.id SET t.a = 1 WHERE u.id = 1", "write writes"),
    ("UPDATE zz_cls_t, zz_cls_u SET zz_cls_t.a = zz_cls_u.id WHERE zz_cls_t.id = zz_cls_u.t_id", "write writes"),
    ("UPDATE zz_cls_t SET a = zz_cls_f() WHERE id = 1", "write writes code udf"),
    ("UPDATE zz_cls_t, zz_cls_u SET zz_cls_t.a = 0 WHERE zz_cls_u.id = 1", "write update-all:others writes"),
    ("UPDATE zz_cls_t t JOIN zz_cls_u u ON u.id = 1 SET t.a = 0 WHERE u.t_id = 2", "write update-all:others writes"),
    ("UPDATE zz_cls_t, zz_cls_u SET a = 0 WHERE zz_cls_u.id = 1", "write writes"),
    ("UPDATE zz_cls_t t, zz_cls_u u SET t.a = u.id WHERE u.id = 1", "write update-all:others writes"),
    ("UPDATE zz_cls_t", "unknown unrecognized"),
    // DELETE.
    ("DELETE FROM zz_cls_t WHERE id = 1", "write writes"),
    ("DELETE FROM zz_cls_t", "write delete-all:missing writes"),
    ("delete from zz_cls_t", "write delete-all:missing writes"),
    ("DELETE FROM zz_cls_t LIMIT 1", "write delete-all:missing writes"),
    ("DELETE FROM zz_cls_t ORDER BY id LIMIT 1", "write delete-all:missing writes"),
    ("DELETE FROM zz_cls_t WHERE 1", "write delete-all:always writes"),
    ("DELETE FROM zz_cls_t WHERE a = a", "write delete-all:always writes"),
    ("DELETE FROM zz_cls_t WHERE ((1 = 1))", "write delete-all:always writes"),
    ("DELETE FROM zz_cls_t WHERE 0", "write delete-all:nocol writes"),
    ("DELETE FROM zz_cls_t WHERE EXISTS (SELECT 1)", "write delete-all:nocol writes"),
    ("DELETE FROM zz_cls_t WHERE id IN (SELECT t_id FROM zz_cls_u)", "write writes"),
    ("DELETE LOW_PRIORITY QUICK IGNORE FROM zz_cls_t WHERE id = 1", "write writes"),
    ("DELETE FROM zz_cls_t PARTITION (p0) WHERE id = 1", "write writes norun"),
    ("DELETE zz_cls_t FROM zz_cls_t JOIN zz_cls_u ON zz_cls_u.t_id = zz_cls_t.id", "write delete-all:missing writes"),
    ("DELETE t, u FROM zz_cls_t t JOIN zz_cls_u u ON u.t_id = t.id WHERE t.id = 1", "write writes"),
    ("DELETE FROM t USING zz_cls_t AS t JOIN zz_cls_u AS u ON u.t_id = t.id", "write delete-all:missing writes"),
    ("DELETE FROM zz_cls_t USING zz_cls_t JOIN zz_cls_u ON zz_cls_u.t_id = zz_cls_t.id WHERE zz_cls_u.id = 1", "write writes"),
    ("DELETE FROM zz_cls_t /* WHERE id = 1 */", "write delete-all:missing writes"),
    ("DELETE FROM zz_cls_t -- WHERE id = 1", "write delete-all:missing writes"),
    ("DELETE FROM zz_cls_t WHERE b = 'x' # comment", "write writes"),
    ("DELETE zz_cls_t FROM zz_cls_t, zz_cls_u WHERE zz_cls_u.id = 1", "write delete-all:others writes"),
    ("DELETE t FROM zz_cls_t t JOIN zz_cls_u u ON u.id = 1 WHERE u.t_id = 2", "write delete-all:others writes"),
    ("DELETE FROM zz_cls_t USING zz_cls_t, zz_cls_u WHERE zz_cls_u.id = 1", "write delete-all:others writes"),
    ("DELETE zz_cls_t.* FROM zz_cls_t, zz_cls_u WHERE `zz_cls_u`.`id` = 1", "write delete-all:others writes"),
    ("DELETE zz_cls_t FROM zz_cls_t, zz_cls_u WHERE zz_cls_u.t_id = zz_cls_t.id", "write writes"),
    ("DELETE zz_cls_t FROM zz_cls_t, zz_cls_u WHERE id = 1", "write writes"),
    ("DELETE zz_cls_t FROM zz_cls_t JOIN zz_cls_u USING (id) WHERE zz_cls_u.id = 1", "write writes"),
    ("DELETE t FROM zz_cls_t t JOIN zz_cls_u u ON u.t_id = t.id WHERE u.id = 1", "write writes"),
    ("DELETE FROM zz_cls_t WHERE `id` = id", "write delete-all:always writes"),
    ("DELETE FROM `zz_cls_t` WHERE zz_cls_t.id = `ZZ_CLS_T`.id", "write delete-all:always writes"),
    // LOAD.
    ("LOAD DATA INFILE '/tmp/zz_cls_in' INTO TABLE zz_cls_t", "write file-access writes"),
    ("LOAD DATA LOCAL INFILE '/tmp/zz_cls_in' INTO TABLE zz_cls_t", "write file-access writes norun"),
    ("LOAD XML INFILE '/tmp/zz_cls_in' INTO TABLE zz_cls_t", "write file-access writes"),
    ("LOAD INDEX INTO CACHE zz_cls_t", "maint commit"),
    // CREATE.
    ("CREATE TABLE zz_cls_new (a INT)", "ddl commit"),
    ("CREATE TABLE IF NOT EXISTS zz_cls_new (a INT PRIMARY KEY, b VARCHAR(10) DEFAULT 'x', KEY k (b))", "ddl commit"),
    ("CREATE TABLE zz_cls_new (a INT, CONSTRAINT c CHECK (a > 0), FOREIGN KEY (a) REFERENCES zz_cls_t (id))", "ddl commit"),
    ("CREATE TABLE zz_cls_new LIKE zz_cls_t", "ddl commit"),
    ("CREATE TABLE zz_cls_new AS SELECT * FROM zz_cls_t", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new SELECT * FROM zz_cls_t", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new (x INT) SELECT id AS x FROM zz_cls_t", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new (SELECT id FROM zz_cls_t)", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new AS TABLE zz_cls_t", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new IGNORE SELECT * FROM zz_cls_t", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new AS WITH c AS (SELECT 1 AS n) SELECT * FROM c", "ddl writes commit"),
    ("CREATE TABLE zz_cls_new AS SELECT LOAD_FILE('/etc/hostname') AS f", "ddl server-file writes commit"),
    ("CREATE TEMPORARY TABLE zz_cls_tmp (a INT)", "ddl"),
    ("CREATE TEMPORARY TABLE zz_cls_tmp AS SELECT * FROM zz_cls_t", "ddl writes"),
    ("CREATE INDEX zz_cls_i ON zz_cls_t (b)", "ddl commit"),
    ("CREATE UNIQUE INDEX zz_cls_i ON zz_cls_t (b(5))", "ddl commit"),
    ("CREATE INDEX zz_cls_i ON zz_cls_t ((a + 1))", "ddl commit"),
    ("CREATE VIEW zz_cls_v2 AS SELECT * FROM zz_cls_t", "ddl commit"),
    ("CREATE OR REPLACE VIEW zz_cls_v2 (x) AS SELECT id FROM zz_cls_t", "ddl commit"),
    ("CREATE ALGORITHM = MERGE SQL SECURITY INVOKER VIEW zz_cls_v2 AS SELECT LOAD_FILE('/x')", "ddl commit"),
    ("CREATE DATABASE zz_cls_db", "ddl commit"),
    ("CREATE SCHEMA IF NOT EXISTS zz_cls_db", "ddl commit"),
    ("CREATE PROCEDURE zz_cls_p2() SELECT 1", "ddl commit"),
    ("CREATE PROCEDURE zz_cls_p2() BEGIN DELETE FROM zz_cls_t; SELECT LOAD_FILE('/x'); END", "ddl commit"),
    ("CREATE DEFINER = CURRENT_USER PROCEDURE zz_cls_p2(IN n INT)\nBEGIN\n  DECLARE v INT DEFAULT 0;\n  SET v = n;\n  SELECT v;\nEND", "ddl commit"),
    ("CREATE DEFINER = `root`@`%` PROCEDURE zz_cls_p2() SELECT 1", "ddl commit"),
    ("CREATE FUNCTION zz_cls_f2() RETURNS INT DETERMINISTIC RETURN 1", "ddl commit"),
    ("CREATE FUNCTION zz_cls_f2(x INT) RETURNS INT DETERMINISTIC BEGIN RETURN x + 1; END", "ddl commit"),
    ("CREATE TRIGGER zz_cls_tr BEFORE INSERT ON zz_cls_t FOR EACH ROW SET NEW.a = 1", "ddl commit"),
    ("CREATE TRIGGER zz_cls_tr BEFORE UPDATE ON zz_cls_t FOR EACH ROW BEGIN IF NEW.a < 0 THEN SET NEW.a = 0; END IF; END", "ddl commit"),
    ("CREATE EVENT zz_cls_e ON SCHEDULE EVERY 1 DAY DO DELETE FROM zz_cls_t", "ddl delete-all:missing commit"),
    ("CREATE EVENT zz_cls_e ON SCHEDULE AT CURRENT_TIMESTAMP DO DELETE FROM zz_cls_t WHERE id = 1", "ddl commit"),
    ("CREATE EVENT zz_cls_e ON SCHEDULE EVERY 1 DAY DO BEGIN DELETE FROM zz_cls_t WHERE id = 1; END", "ddl procedural commit"),
    ("CREATE EVENT zz_cls_e ON SCHEDULE EVERY 1 DAY DO SELECT LOAD_FILE('/x')", "ddl server-file commit"),
    ("ALTER EVENT zz_cls_e DO TRUNCATE zz_cls_t", "ddl truncate commit norun"),
    ("ALTER EVENT zz_cls_e RENAME TO zz_cls_e2 DO DELETE FROM zz_cls_t", "ddl delete-all:missing commit norun"),
    ("ALTER EVENT zz_cls_e DO RENAME TABLE zz_cls_t TO zz_cls_t9", "ddl rename commit norun"),
    ("CREATE EVENT zz_cls_e ON SCHEDULE EVERY 1 DAY DO CREATE EVENT zz_cls_e2 ON SCHEDULE EVERY 1 DAY DO SELECT 1", "ddl unrecognized commit norun"),
    ("CREATE FUNCTION zz_cls_udf RETURNS STRING SONAME 'zz.so'", "maint server-command commit norun"),
    ("CREATE AGGREGATE FUNCTION zz_cls_udf RETURNS INTEGER SONAME 'zz.so'", "maint server-command commit norun"),
    ("CREATE USER zz_cls_user IDENTIFIED BY 'zz'", "ddl privileges commit"),
    ("CREATE ROLE zz_cls_role", "ddl privileges commit"),
    ("CREATE TABLESPACE zz_cls_ts ADD DATAFILE 'zz_cls_ts.ibd'", "ddl commit norun"),
    ("CREATE SERVER zz_cls_s FOREIGN DATA WRAPPER mysql OPTIONS (HOST 'x')", "ddl commit norun"),
    ("CREATE SPATIAL REFERENCE SYSTEM 4120999 NAME 'zz' DEFINITION 'x'", "ddl commit norun"),
    ("CREATE RESOURCE GROUP zz_cls_rg TYPE = USER", "ddl commit norun"),
    ("CREATE", "unknown unrecognized"),
    ("CREATE WIDGET zz_cls_w", "unknown unrecognized"),
    // ALTER.
    ("ALTER TABLE zz_cls_t ADD COLUMN zz_c INT", "ddl commit"),
    ("ALTER TABLE zz_cls_t ADD INDEX zz_i (b), ALGORITHM = INPLACE, LOCK = NONE", "ddl commit"),
    ("ALTER TABLE zz_cls_t ALTER COLUMN a SET DEFAULT 1", "ddl commit"),
    ("ALTER TABLE zz_cls_t ALTER COLUMN a DROP DEFAULT", "ddl commit"),
    ("ALTER TABLE zz_cls_t ALTER a DROP DEFAULT", "ddl commit"),
    ("ALTER TABLE zz_cls_t DROP COLUMN a", "ddl drop-column commit"),
    ("ALTER TABLE zz_cls_t DROP a", "ddl drop-column commit"),
    ("ALTER TABLE zz_cls_t ADD COLUMN zz_c INT, DROP COLUMN a", "ddl drop-column commit"),
    ("ALTER TABLE zz_cls_t DROP INDEX zz_cls_a", "ddl drop commit"),
    ("ALTER TABLE zz_cls_t DROP KEY zz_cls_a", "ddl drop commit"),
    ("ALTER TABLE zz_cls_t DROP PRIMARY KEY", "ddl drop commit"),
    ("ALTER TABLE zz_cls_u DROP FOREIGN KEY zz_cls_fk", "ddl drop commit"),
    ("ALTER TABLE zz_cls_t DROP CHECK zz_c", "ddl drop commit"),
    ("ALTER TABLE zz_cls_t DROP CONSTRAINT zz_c", "ddl drop commit"),
    ("ALTER TABLE zz_cls_t DROP PARTITION p0", "ddl drop commit norun"),
    ("ALTER TABLE zz_cls_t MODIFY a BIGINT", "ddl alter-type commit"),
    ("ALTER TABLE zz_cls_t MODIFY COLUMN b VARCHAR(5)", "ddl alter-type commit"),
    ("ALTER TABLE zz_cls_t CHANGE a a2 INT", "ddl alter-type commit"),
    ("ALTER TABLE zz_cls_t CHANGE COLUMN a a INT NOT NULL", "ddl alter-type commit"),
    ("ALTER TABLE zz_cls_t CONVERT TO CHARACTER SET latin1", "ddl alter-type commit"),
    ("ALTER TABLE zz_cls_t RENAME TO zz_cls_t9", "ddl rename commit"),
    ("ALTER TABLE zz_cls_t RENAME AS zz_cls_t9", "ddl rename commit"),
    ("ALTER TABLE zz_cls_t RENAME COLUMN a TO a9", "ddl rename commit"),
    ("ALTER TABLE zz_cls_t RENAME INDEX zz_cls_a TO zz_cls_a9", "ddl rename commit"),
    ("ALTER TABLE zz_cls_t RENAME COLUMN a TO a9, DROP COLUMN b", "ddl drop-column commit"),
    ("ALTER TABLE zz_cls_t TRUNCATE PARTITION p0", "ddl truncate commit norun"),
    ("ALTER TABLE zz_cls_t DISCARD TABLESPACE", "ddl drop commit"),
    ("ALTER TABLE zz_cls_t EXCHANGE PARTITION p0 WITH TABLE zz_cls_u", "ddl drop commit norun"),
    ("ALTER TABLE zz_cls_t REMOVE PARTITIONING", "ddl drop commit norun"),
    ("ALTER TABLE zz_cls_t ENGINE = InnoDB", "ddl commit"),
    ("ALTER TABLE zz_cls_t ENGINE = BLACKHOLE", "ddl truncate commit"),
    ("ALTER TABLE zz_cls_t ENGINE BLACKHOLE", "ddl truncate commit"),
    ("ALTER TABLE zz_cls_t ENGINE = 'BLACKHOLE'", "ddl truncate commit"),
    ("ALTER TABLE zz_cls_t ENGINE = `blackhole`", "ddl truncate commit"),
    ("ALTER TABLE zz_cls_t COMMENT 'drop me'", "ddl commit"),
    ("ALTER TABLE zz_cls_t ADD COLUMN zz_c INT DEFAULT (ABS(1))", "ddl commit"),
    ("ALTER DATABASE zz_classify CHARACTER SET utf8mb4", "ddl commit"),
    ("ALTER VIEW zz_cls_v AS SELECT id, a FROM zz_cls_t", "ddl commit"),
    ("ALTER PROCEDURE zz_cls_p COMMENT 'x'", "ddl commit"),
    ("ALTER EVENT zz_cls_e RENAME TO zz_cls_e2", "ddl rename commit norun"),
    ("ALTER USER CURRENT_USER IDENTIFIED BY 'zz'", "ddl privileges commit"),
    ("ALTER USER zz_cls_user ACCOUNT LOCK", "ddl privileges commit"),
    ("ALTER INSTANCE ROTATE INNODB MASTER KEY", "maint server-command commit"),
    ("ALTER TABLESPACE zz_cls_ts RENAME TO zz_cls_ts2", "ddl rename commit norun"),
    ("ALTER", "unknown unrecognized"),
    // DROP, RENAME, TRUNCATE.
    ("DROP TABLE zz_cls_t", "ddl drop commit"),
    ("DROP TABLE IF EXISTS zz_cls_new", "ddl drop commit"),
    ("DROP TABLE zz_cls_t, zz_cls_u", "ddl drop commit"),
    ("DROP TEMPORARY TABLE IF EXISTS zz_cls_tmp", "ddl drop"),
    ("DROP VIEW zz_cls_v", "ddl drop commit"),
    ("DROP DATABASE zz_cls_db", "ddl drop commit"),
    ("DROP SCHEMA IF EXISTS zz_cls_db", "ddl drop commit"),
    ("DROP INDEX zz_cls_a ON zz_cls_t", "ddl drop commit"),
    ("DROP PROCEDURE zz_cls_p", "ddl drop commit"),
    ("DROP FUNCTION IF EXISTS zz_cls_f", "ddl drop commit"),
    ("DROP TRIGGER IF EXISTS zz_cls_tr", "ddl drop commit"),
    ("DROP EVENT IF EXISTS zz_cls_e", "ddl drop commit"),
    ("DROP USER zz_cls_user", "ddl drop commit"),
    ("DROP ROLE zz_cls_role", "ddl drop commit"),
    ("DROP PREPARE zz_s", "session ro"),
    ("DEALLOCATE PREPARE zz_s", "session ro"),
    ("RENAME TABLE zz_cls_t TO zz_cls_t9", "ddl rename commit"),
    ("RENAME TABLE zz_cls_t TO zz_cls_t9, zz_cls_u TO zz_cls_t", "ddl rename commit"),
    ("RENAME USER zz_cls_user TO zz_cls_user2", "ddl rename commit"),
    ("TRUNCATE TABLE zz_cls_t", "ddl truncate writes commit"),
    ("TRUNCATE zz_cls_t", "ddl truncate writes commit"),
    ("SELECT TRUNCATE(1.5, 0)", "read ro"),
    // Privileges.
    ("GRANT SELECT ON zz_classify.* TO zz_cls_user", "ddl privileges commit"),
    ("GRANT ALL ON *.* TO zz_cls_user WITH GRANT OPTION", "ddl privileges commit"),
    ("GRANT zz_cls_role TO zz_cls_user", "ddl privileges commit"),
    ("REVOKE SELECT ON zz_classify.* FROM zz_cls_user", "ddl privileges commit"),
    ("REVOKE ALL PRIVILEGES, GRANT OPTION FROM zz_cls_user", "ddl privileges commit"),
    ("SET PASSWORD = 'zz'", "ddl privileges commit"),
    ("SET PASSWORD FOR zz_cls_user = 'zz'", "ddl privileges commit"),
    ("SET DEFAULT ROLE ALL TO zz_cls_user", "ddl privileges commit norun"),
    ("SET ROLE ALL", "session ro"),
    ("SET ROLE NONE", "session ro"),
    // Transactions.
    ("START TRANSACTION", "tx commit ro"),
    ("START TRANSACTION READ ONLY", "tx commit ro"),
    ("START TRANSACTION READ WRITE", "tx rw commit"),
    ("START TRANSACTION WITH CONSISTENT SNAPSHOT", "tx commit ro"),
    ("START TRANSACTION WITH CONSISTENT SNAPSHOT, READ WRITE", "tx rw commit"),
    ("start transaction read write", "tx rw commit"),
    ("BEGIN", "tx commit ro"),
    ("BEGIN WORK", "tx commit ro"),
    ("BEGIN SELECT 1", "unknown unrecognized"),
    ("COMMIT", "tx ro"),
    ("COMMIT WORK", "tx ro"),
    ("COMMIT AND NO CHAIN NO RELEASE", "tx ro"),
    ("ROLLBACK", "tx ro"),
    ("ROLLBACK WORK", "tx ro"),
    ("ROLLBACK TO SAVEPOINT zz_sp", "tx ro"),
    ("ROLLBACK TO zz_sp", "tx ro"),
    ("SAVEPOINT zz_sp", "tx ro"),
    ("RELEASE SAVEPOINT zz_sp", "tx ro"),
    ("RELEASE zz_sp", "unknown unrecognized"),
    ("SET TRANSACTION READ ONLY", "tx ro"),
    ("SET TRANSACTION ISOLATION LEVEL READ COMMITTED", "tx ro"),
    ("SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY", "tx ro"),
    ("SET TRANSACTION READ WRITE", "tx rw"),
    ("SET SESSION TRANSACTION READ WRITE", "tx rw"),
    ("SET SESSION TRANSACTION `READ` WRITE", "unknown unrecognized"),
    ("START TRANSACTION `READ` WRITE", "unknown unrecognized"),
    ("SET LOCAL TRANSACTION READ WRITE", "tx rw"),
    ("SET GLOBAL TRANSACTION READ WRITE", "maint server-command commit"),
    ("SET autocommit = 0", "tx ro"),
    ("SET autocommit = 1", "tx commit ro"),
    ("SET autocommit = ON", "tx commit ro"),
    ("SET autocommit = DEFAULT", "tx commit ro"),
    ("SET @@autocommit = OFF", "tx ro"),
    ("SET SESSION autocommit = 'OFF'", "tx ro"),
    ("XA START 'zz'", "tx server-command"),
    ("XA END 'zz'", "tx server-command"),
    ("XA PREPARE 'zz'", "tx server-command"),
    ("XA COMMIT 'zz'", "tx server-command"),
    ("XA ROLLBACK 'zz'", "tx server-command"),
    ("UNLOCK TABLES", "tx ro"),
    ("UNLOCK INSTANCE", "tx ro"),
    // Read-only switches.
    ("SET transaction_read_only = OFF", "session rw"),
    ("SET transaction_read_only = 0", "session rw"),
    ("SET SESSION transaction_read_only = FALSE", "session rw"),
    ("SET @@transaction_read_only = 'OFF'", "session rw"),
    ("SET @@session.transaction_read_only = 0", "session rw"),
    ("SET @@SESSION.TRANSACTION_READ_ONLY = 0", "session rw"),
    ("SET LOCAL tx_read_only = 0", "session rw"),
    ("SET transaction_read_only = DEFAULT", "session rw"),
    ("SET transaction_read_only = @x", "session rw"),
    ("SET transaction_read_only = ON", "session ro"),
    ("SET @@transaction_read_only = 1", "session ro"),
    ("SET GLOBAL transaction_read_only = OFF", "maint server-command commit"),
    ("SET @@global.transaction_read_only = OFF", "maint server-command commit"),
    ("SET sql_select_limit = 10, transaction_read_only = OFF", "session rw"),
    ("SET @x = 1, transaction_read_only = 0", "session rw"),
    // Settings.
    ("SET @x = 1", "session ro"),
    ("SET @x := 1", "session ro"),
    ("SET @x = 1, @y = 'a'", "session ro"),
    ("SET @`x y` = 1, @'z' = 2", "session ro"),
    ("SET @x = (SELECT MAX(id) FROM zz_cls_t)", "session ro"),
    ("SET @x = zz_cls_f()", "session code udf"),
    ("SET sql_select_limit = 100", "session ro"),
    ("SET SESSION max_execution_time = 1000", "session ro"),
    ("SET @@session.time_zone = '+00:00'", "session ro"),
    ("SET @@time_zone = 'UTC', @@lc_time_names = 'en_US'", "session ro"),
    ("SET LOCAL group_concat_max_len = 100000", "session"),
    ("SET sql_select_limit = DEFAULT", "session ro"),
    ("SET optimizer_switch = 'index_merge=off'", "session ro"),
    ("SET transaction_isolation = 'READ-COMMITTED'", "session ro"),
    ("SET NAMES utf8mb4", "session ro"),
    ("SET NAMES 'utf8mb4' COLLATE 'utf8mb4_bin'", "session ro"),
    ("SET NAMES utf8", "session ro"),
    ("SET CHARACTER SET utf8mb4", "session ro"),
    ("SET CHARSET utf8mb4", "session ro"),
    ("SET NAMES utf8mb4, transaction_read_only = 0", "session rw"),
    ("SET NAMES utf8mb4, sql_log_bin = 0", "session setting"),
    ("SET @x = 1, NAMES gbk", "session setting"),
    ("SET CHARACTER SET utf8mb4, @@session.transaction_read_only = OFF", "session rw"),
    ("SET NAMES utf8mb4 COLLATE utf8mb4_bin, @x = 1", "session ro"),
    ("SET NAMES utf8mb4 utf8mb4", "unknown unrecognized"),
    ("SET ROLE ALL, transaction_read_only = 0", "unknown unrecognized rw"),
    ("SELECT 1 INTO @x FROM zz_cls_t INTO OUTFILE '/tmp/zz_cls_out'", "write file-access norun"),
    ("SELECT 1 INTO @x FROM (SELECT 1 INTO @y) AS d", "unknown unrecognized"),
    ("SET character_set_client = utf8mb4", "session ro"),
    ("SET NAMES gbk", "session setting"),
    ("SET NAMES sjis", "session setting"),
    ("SET NAMES DEFAULT", "session setting"),
    ("SET CHARACTER SET big5", "session setting"),
    ("SET character_set_client = gbk", "session setting"),
    ("SET sql_mode = 'ANSI_QUOTES'", "session setting"),
    ("SET SESSION sql_mode = ''", "session setting"),
    ("SET @@sql_mode = 'NO_BACKSLASH_ESCAPES'", "session setting"),
    ("SET sql_log_bin = 0", "session setting"),
    ("SET foreign_key_checks = 0", "session setting"),
    ("SET unique_checks = 0", "session setting"),
    ("SET sql_safe_updates = 0", "session setting"),
    ("SET gtid_next = 'AUTOMATIC'", "session setting"),
    ("SET session_track_schema = OFF", "session setting"),
    ("SET resultset_metadata = NONE", "session setting"),
    ("SET timestamp = 1", "session"),
    ("SET innodb_strict_mode = OFF", "session"),
    ("SET a.b = 1", "session"),
    ("SET STATEMENT max_statement_time = 1 FOR DELETE FROM zz_cls_t", "unknown unrecognized"),
    ("SET @x = 1, STATEMENT sql_select_limit = 1 FOR DELETE FROM zz_cls_t", "unknown unrecognized"),
    ("SET @@session.sql_select_limit .x = 1", "unknown unrecognized"),
    ("CREATE TABLE event (a INT); DROP TABLE zz_cls_u", "ddl drop commit norun"),
    ("CREATE TABLE trigger AS SELECT LOAD_FILE('/etc/hostname')", "ddl server-file writes commit norun"),
    ("ALTER TABLE event DROP COLUMN a", "ddl drop-column commit norun"),
    ("SET GLOBAL max_connections = 151", "maint server-command commit"),
    ("SET @@global.max_connections = 151", "maint server-command commit"),
    ("SET PERSIST max_connections = 151", "maint server-command commit"),
    ("SET PERSIST_ONLY max_connections = 151", "maint server-command commit"),
    ("SET @@persist.max_connections = 151", "maint server-command commit"),
    ("SET GLOBAL max_connections = 151, sql_select_limit = 10", "maint server-command commit"),
    ("SET sql_select_limit = 10, GLOBAL max_connections = 151", "maint server-command commit"),
    ("SET GLOBAL max_connections = 151, SESSION sql_select_limit = 10", "maint server-command commit"),
    ("SET RESOURCE GROUP zz_rg", "maint server-command commit"),
    ("SET `sql_mode` = ''", "unknown unrecognized"),
    ("SET", "unknown unrecognized"),
    ("SET x", "unknown unrecognized"),
    ("USE zz_classify", "session ro"),
    ("USE `zz_classify`", "session ro"),
    // Locks.
    ("LOCK TABLES zz_cls_t READ", "write locks commit srvok"),
    ("LOCK TABLES zz_cls_t WRITE", "write locks commit"),
    ("LOCK TABLE zz_cls_t AS t READ LOCAL, zz_cls_u WRITE", "write locks commit"),
    ("LOCK INSTANCE FOR BACKUP", "maint locks"),
    ("HANDLER zz_cls_t OPEN", "write locks srvok"),
    ("HANDLER zz_cls_t READ FIRST", "write locks norun"),
    ("HANDLER zz_cls_t CLOSE", "write locks norun"),
    ("FLUSH TABLES WITH READ LOCK", "maint locks commit"),
    ("FLUSH TABLES zz_cls_t WITH READ LOCK", "maint locks commit"),
    ("FLUSH TABLES zz_cls_t FOR EXPORT", "maint locks commit"),
    // Procedures and prepared statements.
    ("CALL zz_cls_p()", "proc procedural code"),
    ("CALL zz_cls_p", "proc procedural code"),
    ("CALL zz_classify.zz_cls_p()", "proc procedural code"),
    ("PREPARE zz_s FROM 'SELECT 1'", "session dynamic-sql"),
    ("PREPARE zz_s FROM @q", "session dynamic-sql"),
    ("EXECUTE zz_s", "unknown unknown-prepared"),
    ("EXECUTE zz_s USING @a, @b", "unknown unknown-prepared"),
    // Maintenance.
    ("ANALYZE TABLE zz_cls_t", "maint commit"),
    ("ANALYZE LOCAL TABLE zz_cls_t", "maint commit"),
    ("ANALYZE TABLE zz_cls_t UPDATE HISTOGRAM ON a WITH 10 BUCKETS", "maint commit"),
    ("ANALYZE TABLE zz_cls_t DROP HISTOGRAM ON a", "maint commit"),
    ("OPTIMIZE TABLE zz_cls_t", "maint commit"),
    ("OPTIMIZE NO_WRITE_TO_BINLOG TABLE zz_cls_t", "maint commit"),
    ("CHECK TABLE zz_cls_t", "maint commit"),
    ("CHECK TABLE zz_cls_t FOR UPGRADE QUICK", "maint commit"),
    ("CHECKSUM TABLE zz_cls_t", "maint commit"),
    ("REPAIR TABLE zz_cls_t", "maint commit"),
    ("REPAIR TABLE zz_cls_t USE_FRM", "maint commit"),
    ("CACHE INDEX zz_cls_t IN zz_cache", "maint commit"),
    // Statements on the whole server.
    ("KILL 1", "maint server-command commit"),
    ("KILL QUERY 1", "maint server-command commit"),
    ("KILL CONNECTION 1", "maint server-command commit"),
    ("SHUTDOWN", "maint server-command commit"),
    ("RESTART", "maint server-command commit"),
    ("FLUSH PRIVILEGES", "maint server-command commit"),
    ("FLUSH LOGS", "maint server-command commit"),
    ("FLUSH STATUS", "maint server-command commit"),
    ("FLUSH TABLES", "maint server-command commit"),
    ("FLUSH LOCAL HOSTS", "maint server-command commit"),
    ("RESET MASTER", "maint server-command commit"),
    ("RESET BINARY LOGS AND GTIDS", "maint server-command commit"),
    ("RESET REPLICA ALL", "maint server-command commit"),
    ("RESET PERSIST", "maint server-command commit"),
    ("PURGE BINARY LOGS TO 'binlog.000001'", "maint server-command commit"),
    ("PURGE BINARY LOGS BEFORE NOW()", "maint server-command commit"),
    ("CHANGE REPLICATION SOURCE TO SOURCE_HOST = 'x'", "maint server-command commit"),
    ("CHANGE MASTER TO MASTER_HOST = 'x'", "maint server-command commit"),
    ("CHANGE REPLICATION FILTER REPLICATE_DO_DB = (zz)", "maint server-command commit"),
    ("START REPLICA", "maint server-command commit"),
    ("START SLAVE", "maint server-command commit"),
    ("STOP REPLICA", "maint server-command commit"),
    ("START GROUP_REPLICATION", "maint server-command commit"),
    ("STOP GROUP_REPLICATION", "maint server-command commit"),
    ("INSTALL PLUGIN zz SONAME 'zz.so'", "maint server-command commit"),
    ("UNINSTALL PLUGIN zz", "maint server-command commit"),
    ("INSTALL COMPONENT 'file://component_zz'", "maint server-command commit"),
    ("CLONE LOCAL DATA DIRECTORY = '/tmp/zz'", "maint server-command commit"),
    ("BINLOG 'AAAA'", "unknown server-command"),
    ("IMPORT TABLE FROM '/tmp/zz.sdi'", "ddl commit"),
    // Case, spacing and quoting do not change a verdict.
    ("  \n\tSELECT\n1\n", "read ro"),
    ("sElEcT * fRoM zz_cls_t", "read ro"),
    ("DeLeTe FrOm zz_cls_t", "write delete-all:missing writes"),
    ("DELETE\nFROM\nzz_cls_t\n", "write delete-all:missing writes"),
    ("DELETE FROM `zz_cls_t`", "write delete-all:missing writes"),
    ("DELETE FROM zz_classify.zz_cls_t", "write delete-all:missing writes"),
    ("DELETE FROM `zz_classify`.`zz_cls_t` WHERE `id` = 1", "write writes"),
    ("UPDATE `zz_cls_t` SET `a` = 1 WHERE `id` = 1", "write writes"),
    ("SELECT `select` FROM (SELECT 1 AS `select`) AS `from`", "read ro"),
    ("SELECT t.`delete` FROM (SELECT 1 AS `delete`) AS t", "read ro"),
    ("SELECT d.update FROM (SELECT 1 AS `update`) AS d", "read ro"),
    ("SELECT 'DELETE FROM zz_cls_t'", "read ro"),
    ("SELECT \"DROP TABLE zz_cls_t\"", "read ro"),
    ("SELECT `DROP TABLE zz_cls_t` FROM (SELECT 1 AS `DROP TABLE zz_cls_t`) AS x", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE b = 'x\\' OR 1=1 -- '", "read ro"),
    ("SELECT * FROM zz_cls_t WHERE b = 'a''; DROP TABLE zz_cls_t; --'", "read ro"),
];
