use super::super::tests::{Case, check};

/// `r`, `J`, `gJ`, `~`, `gu` `gU` `g~` and `>` `<` with motions, text objects, counts and
/// doubled, as Vim does them (with a 4-column indent written with spaces).
#[test]
fn edits_as_vim() {
    const CASES: &[Case] = &[
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "rx",
            "one two\n  thxee four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "3rx",
            "one two\n  thxxx four\nfive six\nseven",
            (1, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "9rx",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "r<CR>",
            "one two\n  th\n  ee four\nfive six\nseven",
            (2, 1),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "2r<CR>",
            "one two\n  th\n  e four\nfive six\nseven",
            (2, 1),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "r\u{D55C}",
            "one two\n  th\u{D55C}ee four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "rx.",
            "one two\n  thxee four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "r<Tab>",
            "one two\n  th    ee four\nfive six\nseven",
            (1, 7),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 3),
            "r<CR>",
            "one\ntwo\n  three four\nfive six\nseven",
            (1, 0),
            None,
        ),
        ("one two\n  three four\nfive six\nseven", (0, 3), "J", "one two three four\nfive six\nseven", (0, 7), None),
        ("one two\n  three four\nfive six\nseven", (0, 3), "3J", "one two three four five six\nseven", (0, 18), None),
        ("one two\n  three four\nfive six\nseven", (0, 3), "9J", "one two three four five six seven", (0, 27), None),
        ("one two\n  three four\nfive six\nseven", (0, 3), "gJ", "one two  three four\nfive six\nseven", (0, 7), None),
        ("one two\n  three four\nfive six\nseven", (0, 3), "3gJ", "one two  three fourfive six\nseven", (0, 19), None),
        ("one two\n  three four\nfive six\nseven", (0, 3), "J.", "one two three four five six\nseven", (0, 18), None),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 3),
            "Ju",
            "one two\n  three four\nfive six\nseven",
            (0, 3),
            None,
        ),
        ("one two\n  three four\nfive six\nseven", (3, 0), "J", "one two\n  three four\nfive six\nseven", (3, 0), None),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            "gJ",
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            None,
        ),
        ("one two\n  three four\nfive six\nseven", (3, 0), "~", "one two\n  three four\nfive six\nSeven", (3, 1), None),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            "r<CR>",
            "one two\n  three four\nfive six\n\neven",
            (4, 0),
            None,
        ),
        ("a  \n  b\n)\n\nc", (0, 0), "J", "a  b\n)\n\nc", (0, 3), None),
        ("a  \n  b\n)\n\nc", (0, 0), "2J", "a  b\n)\n\nc", (0, 3), None),
        ("a  \n  b\n)\n\nc", (0, 0), "3J", "a  b)\n\nc", (0, 4), None),
        ("a  \n  b\n)\n\nc", (0, 0), "4J", "a  b)\nc", (0, 4), None),
        ("a  \n  b\n)\n\nc", (0, 0), "5J", "a  b) c", (0, 5), None),
        ("a  \n  b\n)\n\nc", (0, 0), "gJ", "a    b\n)\n\nc", (0, 3), None),
        ("a  \n  b\n)\n\nc", (0, 0), "4gJ", "a    b)\nc", (0, 6), None),
        ("one\n\ntwo", (0, 0), "J", "one\ntwo", (0, 2), None),
        ("one\n\ntwo", (0, 0), "3J", "one two", (0, 3), None),
        ("one\ttab\n\tnext", (0, 0), "J", "one\ttab next", (0, 7), None),
        ("one\ttab\n\tnext", (0, 0), "gJ", "one\ttab\tnext", (0, 7), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "~", "sELECT Foo, ÀÉ ß \u{AC00} x", (0, 1), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "3~", "selECT Foo, ÀÉ ß \u{AC00} x", (0, 3), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "99~", "select fOO, àé ẞ \u{AC00} X", (0, 19), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "~~", "seLECT Foo, ÀÉ ß \u{AC00} x", (0, 2), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "g~w", "select Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "g~~", "select fOO, àé ẞ \u{AC00} X", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gUw", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gUU", "SELECT FOO, ÀÉ ẞ \u{AC00} X", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gUgU", "SELECT FOO, ÀÉ ẞ \u{AC00} X", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "guu", "select foo, àé ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gugu", "select foo, àé ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gUiw", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gu$", "select foo, àé ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "g~iW", "select Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gU3l", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gUe", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "3gUU", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "g~~.", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "gUw.", "SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), None),
        ("SELECT Foo, ÀÉ ß \u{AC00} x", (0, 0), "$~", "SELECT Foo, ÀÉ ß \u{AC00} X", (0, 19), None),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "gUj",
            "one two\n  THREE FOUR\nFIVE SIX\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "gUk",
            "ONE TWO\n  THREE FOUR\nfive six\nseven",
            (0, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "guG",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "g~ip",
            "ONE TWO\n  THREE FOUR\nFIVE SIX\nSEVEN",
            (0, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "gUU",
            "one two\n  THREE FOUR\nfive six\nseven",
            (1, 2),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "2gUU",
            "one two\n  THREE FOUR\nFIVE SIX\nseven",
            (1, 4),
            None,
        ),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">>", "    a\n\tb\n    c\n\n  d", (0, 4), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "3>>", "    a\n        b\n        c\n\n  d", (0, 4), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">j", "    a\n        b\n    c\n\n  d", (0, 4), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">G", "    a\n        b\n        c\n\n      d", (0, 4), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">ip", "    a\n        b\n        c\n\n  d", (0, 4), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "5>>", "    a\n        b\n        c\n\n      d", (0, 4), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">>.", "        a\n\tb\n    c\n\n  d", (0, 8), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "<<", "a\n\tb\n    c\n\n  d", (0, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">>j<<", "    a\nb\n    c\n\n  d", (1, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "j<<", "a\nb\n    c\n\n  d", (1, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "j2<<", "a\nb\nc\n\n  d", (1, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "jj<<", "a\n\tb\nc\n\n  d", (2, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "jj>>", "a\n\tb\n        c\n\n  d", (2, 8), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "<G", "a\nb\nc\n\nd", (0, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "j>>.", "a\n            b\n    c\n\n  d", (1, 12), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "G<<", "a\n\tb\n    c\n\nd", (4, 0), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), "G>>", "a\n\tb\n    c\n\n      d", (4, 6), None),
        ("a\n\tb\n    c\n\n  d", (0, 0), ">}", "    a\n        b\n        c\n\n  d", (0, 4), None),
        ("        x\n      y\n   z", (0, 0), "<<", "    x\n      y\n   z", (0, 4), None),
        ("        x\n      y\n   z", (0, 0), "3<<", "    x\n  y\nz", (0, 4), None),
        ("        x\n      y\n   z", (0, 0), "<j", "    x\n  y\n   z", (0, 4), None),
        ("        x\n      y\n   z", (0, 0), "j>>", "        x\n          y\n   z", (1, 10), None),
        ("        x\n      y\n   z", (0, 0), "jj<<", "        x\n      y\nz", (2, 0), None),
        ("        x\n      y\n   z", (0, 0), "jj>>", "        x\n      y\n       z", (2, 7), None),
    ];
    check(CASES);
}

/// The same edits on a Visual selection.
#[test]
fn edits_in_visual_mode() {
    const CASES: &[Case] = &[
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "v>",
            "one two\n      three four\nfive six\nseven",
            (1, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "V>",
            "one two\n      three four\nfive six\nseven",
            (1, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "Vj>",
            "one two\n      three four\n    five six\nseven",
            (1, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "V3>",
            "one two\n              three four\nfive six\nseven",
            (1, 14),
            None,
        ),
        ("one two\n  three four\nfive six\nseven", (1, 4), "Vj<", "one two\nthree four\nfive six\nseven", (1, 0), None),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vj>",
            "one two\n      three four\n    five six\nseven",
            (1, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vlrx",
            "one two\n  thxxe four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vjrx",
            "one two\n  thxxxxxxxx\nxxxxxsix\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "VjJ",
            "one two\n  three four five six\nseven",
            (1, 12),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vjJ",
            "one two\n  three four five six\nseven",
            (1, 12),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vlu",
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vlU",
            "one two\n  thREe four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vl~",
            "one two\n  thREe four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "Vu",
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "VU",
            "one two\n  THREE FOUR\nfive six\nseven",
            (1, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "Vj~",
            "one two\n  THREE FOUR\nFIVE SIX\nseven",
            (1, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vlgU",
            "one two\n  thREe four\nfive six\nseven",
            (1, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "Vjgu",
            "one two\n  three four\nfive six\nseven",
            (1, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "VjgJ",
            "one two\n  three fourfive six\nseven",
            (1, 12),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "vjgJ",
            "one two\n  three fourfive six\nseven",
            (1, 12),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "v2>.",
            "one two\n                  three four\nfive six\nseven",
            (1, 18),
            None,
        ),
        ("a\n    b\n        c", (1, 0), "V<", "a\nb\n        c", (1, 0), None),
        ("a\n    b\n        c", (1, 0), "V2<", "a\nb\n        c", (1, 0), None),
        ("a\n    b\n        c", (1, 0), "Vj<", "a\nb\n    c", (1, 0), None),
        ("a\n    b\n        c", (1, 0), "Vk>", "    a\n        b\n        c", (0, 4), None),
    ];
    check(CASES);
}

/// Wide characters (CJK, emoji, Hangul) are one grapheme each for `r`, `f`, `t`, `~`, `J` and
/// the objects, as for Vim.
#[test]
fn wide_characters() {
    const CASES: &[Case] = &[
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 4), "rx", "日本語 x ab\n  \u{D55C}\u{AE00} x", (0, 4), None),
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 0), "2r-", "--語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 1), None),
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 0), "f🐘", "日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 4), None),
        (
            "日本語 🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 0),
            "dt🐘",
            "🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 0),
            Some(("日本語 ", false)),
        ),
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 0), "vlrx", "xx語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 0), None),
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 0), "W~", "日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 5), None),
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (0, 4), "J", "日本語 🐘 ab \u{D55C}\u{AE00} x", (0, 8), None),
        (
            "日本語 🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 0),
            "diw",
            " 🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 0),
            Some(("日本語", false)),
        ),
        (
            "日本語 🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 0),
            "dE",
            " 🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 0),
            Some(("日本語", false)),
        ),
        ("日本語 🐘 ab\n  \u{D55C}\u{AE00} x", (1, 2), "fx~", "日本語 🐘 ab\n  \u{D55C}\u{AE00} X", (1, 5), None),
        (
            "日本語 🐘 ab\n  \u{D55C}\u{AE00} x",
            (0, 6),
            "r\u{D55C}",
            "日本語 🐘 \u{D55C}b\n  \u{D55C}\u{AE00} x",
            (0, 6),
            None,
        ),
    ];
    check(CASES);
}
