use super::super::Editor;
use super::super::tests::{Case, at, check, typ};
use super::*;

#[test]
fn word_motions() {
    let mut e = Editor::new("SELECT u.name, x\n\nFROM t");
    typ(&mut e, "w");
    assert_eq!((e.row, e.col), (0, 7));
    typ(&mut e, "w");
    assert_eq!((e.row, e.col), (0, 8));
    typ(&mut e, "ww");
    assert_eq!((e.row, e.col), (0, 13));
    typ(&mut e, "ww");
    assert_eq!((e.row, e.col), (1, 0));
    typ(&mut e, "w");
    assert_eq!((e.row, e.col), (2, 0));
    typ(&mut e, "b");
    assert_eq!((e.row, e.col), (1, 0));
    typ(&mut e, "b");
    assert_eq!((e.row, e.col), (0, 15));
    typ(&mut e, "0e");
    assert_eq!((e.row, e.col), (0, 5));
    typ(&mut e, "G");
    assert_eq!(e.row, 2);
    typ(&mut e, "gg");
    assert_eq!(e.row, 0);
}

/// Motions with counts, at the ends of lines and of the text, as Vim moves.
#[test]
fn motions_with_counts_move_as_vim() {
    const CASES: &[Case] = &[
        (
            "one two\n  three four\nfive six\nseven",
            (0, 4),
            "5j",
            "one two\n  three four\nfive six\nseven",
            (3, 4),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 2),
            "2k",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "3w",
            "one two\n  three four\nfive six\nseven",
            (1, 8),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "3e",
            "one two\n  three four\nfive six\nseven",
            (1, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            "4b",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "3G",
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            "10G",
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (3, 0),
            "2gg",
            "one two\n  three four\nfive six\nseven",
            (1, 2),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (1, 4),
            "2$",
            "one two\n  three four\nfive six\nseven",
            (2, 7),
            None,
        ),
        ("one two\n  three four\nfive six\nseven", (3, 4), "w", "one two\n  three four\nfive six\nseven", (3, 4), None),
        ("one two\n  three four\nfive six\nseven", (3, 4), "e", "one two\n  three four\nfive six\nseven", (3, 4), None),
        ("one two\n  three four\nfive six\nseven", (0, 0), "b", "one two\n  three four\nfive six\nseven", (0, 0), None),
        ("a\n\nb", (0, 0), "w", "a\n\nb", (1, 0), None),
        ("a\n\nb", (2, 0), "b", "a\n\nb", (1, 0), None),
        ("a\n\nb", (0, 0), "e", "a\n\nb", (2, 0), None),
        ("foo(bar, baz)", (0, 0), "3w", "foo(bar, baz)", (0, 7), None),
        ("foo(bar, baz)", (0, 12), "2b", "foo(bar, baz)", (0, 7), None),
        ("foo(bar, baz)", (0, 0), "3e", "foo(bar, baz)", (0, 6), None),
        ("one two\n  three four", (0, 5), "2l", "one two\n  three four", (0, 6), None),
        ("one two\n  three four", (0, 5), "9h", "one two\n  three four", (0, 0), None),
        ("one two\n  three four", (1, 9), "0", "one two\n  three four", (1, 0), None),
        ("one two\n  three four", (1, 9), "^", "one two\n  three four", (1, 2), None),
        ("one two\n  three four", (1, 9), "3<Left><Down>", "one two\n  three four", (1, 6), None),
        ("one two\n  three four", (1, 9), "<Home><Up><End>", "one two\n  three four", (0, 6), None),
    ];
    check(CASES);
}

/// `$` keeps the cursor at the ends of lines going up and down; `j`/`k` keep the column.
#[test]
fn vertical_moves_keep_the_wanted_column() {
    let mut e = at("long line here\nab\nanother long one", (0, 9));
    typ(&mut e, "j");
    assert_eq!((e.row, e.col), (1, 1));
    typ(&mut e, "j");
    assert_eq!((e.row, e.col), (2, 9));
    typ(&mut e, "$2k");
    assert_eq!((e.row, e.col), (0, 13));
}

#[test]
fn operator_ranges_have_their_kind() {
    let mut e = at("one two\n  three four\nfive", (1, 4));
    let mut r = |m, n| e.op_range(m, n, false).map(|r| (r.start, r.end, r.kind));
    use RangeKind::*;
    assert_eq!(r(Motion::WordForward, 1), Some(((1, 4), (1, 8), Exclusive)));
    assert_eq!(r(Motion::WordEnd, 1), Some(((1, 4), (1, 6), Inclusive)));
    assert_eq!(r(Motion::LineEnd, 1), Some(((1, 4), (1, 11), Inclusive)));
    assert_eq!(r(Motion::WordBack, 1), Some(((1, 2), (1, 4), Exclusive)));
    assert_eq!(r(Motion::Down, 1), Some(((1, 4), (2, 4), Linewise)));
    assert_eq!(r(Motion::Right, 99), Some(((1, 4), (1, 12), Exclusive)), "to the end of the line");
    // `w` over the last word of a line ends there; ending at the start of a line from the
    // indent takes the lines whole.
    assert_eq!(r(Motion::WordForward, 2), Some(((1, 4), (1, 12), Exclusive)));
    let mut e = at("a\n\nb", (1, 0));
    let w = e.op_range(Motion::WordForward, 1, false).map(|r| (r.start, r.end, r.kind));
    assert_eq!(w, Some(((1, 0), (1, 0), Linewise)));
    let mut e = at("a", (0, 0));
    assert_eq!(e.op_range(Motion::Left, 1, false), None, "h in the first column");
    assert_eq!(e.op_range(Motion::Down, 1, false), None, "j on the last line");
}

/// `W B E ge gE` with counts, as motions and with operators, as Vim does them; Hangul words
/// are words.
#[test]
fn big_words_and_ends_of_words_back() {
    const CASES: &[Case] = &[
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "W", "foo.bar(baz) -- qux\nlast_word;", (0, 13), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "2W", "foo.bar(baz) -- qux\nlast_word;", (0, 16), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "3W", "foo.bar(baz) -- qux\nlast_word;", (1, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "E", "foo.bar(baz) -- qux\nlast_word;", (0, 11), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "2E", "foo.bar(baz) -- qux\nlast_word;", (0, 14), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "B", "foo.bar(baz) -- qux\nlast_word;", (0, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "ge", "foo.bar(baz) -- qux\nlast_word;", (0, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "gE", "foo.bar(baz) -- qux\nlast_word;", (0, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "dW", "-- qux\nlast_word;", (0, 0), Some(("foo.bar(baz) ", false))),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 0),
            "cW_<Esc>",
            "_ -- qux\nlast_word;",
            (0, 0),
            Some(("foo.bar(baz)", false)),
        ),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "dE", " -- qux\nlast_word;", (0, 0), Some(("foo.bar(baz)", false))),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "dB", "foo.bar(baz) -- qux\nlast_word;", (0, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "dge", "foo.bar(baz) -- qux\nlast_word;", (0, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "dgE", "foo.bar(baz) -- qux\nlast_word;", (0, 0), None),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 0),
            "yW",
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 0),
            Some(("foo.bar(baz) ", false)),
        ),
        ("foo.bar(baz) -- qux\nlast_word;", (0, 0), "4W", "foo.bar(baz) -- qux\nlast_word;", (1, 9), None),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 0),
            "y2E",
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 0),
            Some(("foo.bar(baz) --", false)),
        ),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "B", "foo.bar(baz) -- qux\nlast_word;", (1, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "b", "foo.bar(baz) -- qux\nlast_word;", (1, 0), None),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "ge", "foo.bar(baz) -- qux\nlast_word;", (0, 18), None),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "2ge", "foo.bar(baz) -- qux\nlast_word;", (0, 14), None),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "gE", "foo.bar(baz) -- qux\nlast_word;", (0, 18), None),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "2gE", "foo.bar(baz) -- qux\nlast_word;", (0, 14), None),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (1, 3),
            "dge",
            "foo.bar(baz) -- qu_word;",
            (0, 18),
            Some(("x\nlast", false)),
        ),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (1, 3),
            "dgE",
            "foo.bar(baz) -- qu_word;",
            (0, 18),
            Some(("x\nlast", false)),
        ),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "dB", "foo.bar(baz) -- qux\nt_word;", (1, 0), Some(("las", false))),
        (
            "foo.bar(baz) -- qux\nlast_word;",
            (1, 3),
            "y3B",
            "foo.bar(baz) -- qux\nlast_word;",
            (0, 13),
            Some(("-- qux\nlas", false)),
        ),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "E", "foo.bar(baz) -- qux\nlast_word;", (1, 9), None),
        ("foo.bar(baz) -- qux\nlast_word;", (1, 3), "W", "foo.bar(baz) -- qux\nlast_word;", (1, 9), None),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            "ge",
            "one two\n  three four\nfive six\nseven",
            (1, 11),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            "3ge",
            "one two\n  three four\nfive six\nseven",
            (0, 6),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            "gE",
            "one two\n  three four\nfive six\nseven",
            (1, 11),
            None,
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            "dge",
            "one two\n  three fouive six\nseven",
            (1, 11),
            Some(("r\nf", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            "d2gE",
            "one two\n  threive six\nseven",
            (1, 6),
            Some(("e four\nf", false)),
        ),
        (
            "one two\n  three four\nfive six\nseven",
            (2, 0),
            "9ge",
            "one two\n  three four\nfive six\nseven",
            (0, 0),
            None,
        ),
        ("a\n\nb c", (2, 0), "ge", "a\n\nb c", (1, 0), None),
        ("a\n\nb c", (2, 0), "gE", "a\n\nb c", (1, 0), None),
        ("a\n\nb c", (2, 0), "2ge", "a\n\nb c", (0, 0), None),
        ("a\n\nb c", (2, 0), "dge", "a\n c", (1, 0), Some(("\nb", false))),
        ("a\n\nb c", (2, 0), "B", "a\n\nb c", (1, 0), None),
        ("a\n\nb c", (2, 0), "2B", "a\n\nb c", (0, 0), None),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "W",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 7),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "E",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 5),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "B",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "ge",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 1),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "dW",
            "\u{AC00}\u{B098} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            Some(("\u{B2E4}\u{B77C}\u{B9C8} ", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "dE",
            "\u{AC00}\u{B098}  \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            Some(("\u{B2E4}\u{B77C}\u{B9C8}", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "2W",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (1, 0),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            "gE",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 1),
            None,
        ),
    ];
    check(CASES);
}

/// `f F t T ; ,` with counts, as motions and with operators, as Vim does them: a repeated `t`
/// does not stay next to its character, and the character may be Hangul or a tab.
#[test]
fn find_a_character_on_the_line() {
    const CASES: &[Case] = &[
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "fa",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 7),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "2fa",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 16),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "ta",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 6),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "2ta",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 15),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "f,",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 11),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "fz",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "dfa",
            ".id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            Some(("SELECT a", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "dta",
            "a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            Some(("SELECT ", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "d2f.",
            "name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            Some(("SELECT a.id, b.", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "cf,x<Esc>",
            "x b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            Some(("SELECT a.id,", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "yt,",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            Some(("SELECT a.id", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "fa;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 16),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "fa;;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 16),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "fa;,",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 7),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "ta;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 15),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "ta,",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 6),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "d;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "fa2;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 7),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "ta2;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 15),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 0),
            "t.;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 13),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Fa",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 16),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "2Fa",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 7),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Ta",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 17),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "dFa",
            "SELECT a.id, b.ne\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 16),
            Some(("am", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "dTa",
            "SELECT a.id, b.nae\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 17),
            Some(("m", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Fa;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 7),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Fa,",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 16),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Ta;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 8),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Ta,",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 17),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "Fz",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "yF.",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 14),
            Some((".nam", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 18),
            "F.;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (0, 8),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "fb",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 9),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "Fo",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "tb",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 8),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "To",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "tf",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "Tf",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "dtb",
            "SELECT a.id, b.name\nFROMbar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            Some((" foo(", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "dTo",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "dff",
            "SELECT a.id, b.name\nFROMoo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            Some((" f", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "dtf",
            "SELECT a.id, b.name\nFROMfoo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            Some((" ", false)),
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "tb;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 13),
            None,
        ),
        (
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            "Tf;",
            "SELECT a.id, b.name\nFROM foo(bar, baz) a\n  JOIN t2 b ON (a.x = b.y)\nWHERE a.z IN ('x', 'y')",
            (1, 4),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "f\u{B77C}",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 4),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "t\u{B77C}",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 3),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "f\u{BC14}",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 7),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "df\u{B77C}",
            "\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            Some(("\u{AC00}\u{B098} \u{B2E4}\u{B77C}", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "dt\u{BC14}",
            "\u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            Some(("\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} ", false)),
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "f 3;",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 2),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "f\u{B77C}F\u{AC00}",
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            None,
        ),
        (
            "\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8} \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            "cf\u{B9C8}x<Esc>",
            "x \u{BC14}\n\u{D55C}\u{AE00} \u{D14D}\u{C2A4}\u{D2B8}, \u{B458}\n  \u{C14B} \u{B137}",
            (0, 0),
            Some(("\u{AC00}\u{B098} \u{B2E4}\u{B77C}\u{B9C8}", false)),
        ),
        ("\tone\ttwo\n\t\tthree", (0, 0), "ft", "\tone\ttwo\n\t\tthree", (0, 5), None),
        ("\tone\ttwo\n\t\tthree", (0, 0), "f\t", "\tone\ttwo\n\t\tthree", (0, 4), None),
        ("\tone\ttwo\n\t\tthree", (0, 0), "dt\t", "\ttwo\n\t\tthree", (0, 0), Some(("\tone", false))),
        ("\tone\ttwo\n\t\tthree", (0, 0), "Fo", "\tone\ttwo\n\t\tthree", (0, 0), None),
        ("\tone\ttwo\n\t\tthree", (0, 0), "f<Tab>", "\tone\ttwo\n\t\tthree", (0, 4), None),
    ];
    check(CASES);
}

/// `%` (with a count: that percentage of the lines) and `{` `}`, as motions and with operators,
/// as Vim does them.
#[test]
fn brackets_and_paragraphs() {
    const CASES: &[Case] = &[
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 18),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "%%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 1),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "d%",
            "\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("f(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "y%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("f(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "c%x<Esc>",
            "x\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("f(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 1),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 18),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 1),
            "d%",
            "f\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 5),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 12),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 5),
            "d%",
            "f(a, , (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 5),
            Some(("[b, {c}]", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 9),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 11),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 9),
            "d%",
            "f(a, [b, ], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 9),
            Some(("{c}", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 18),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 1),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 18),
            "d%",
            "f\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            Some(("(a, [b, {c}], (d))", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 3),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 12),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 3),
            "d%",
            "f(a, (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 3),
            Some((", [b, {c}]", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 0),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (3, 0),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 0),
            "d%",
            "f(a, [b, {c}], (d))",
            (0, 0),
            Some(("x = (1 +\n  (2 * 3)\n)", true)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 0),
            "y%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 0),
            Some(("x = (1 +\n  (2 * 3)\n)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 0),
            "c%z<Esc>",
            "f(a, [b, {c}], (d))\nz",
            (1, 0),
            Some(("x = (1 +\n  (2 * 3)\n)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (3, 0),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 4),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (3, 0),
            "d%",
            "f(a, [b, {c}], (d))\nx = ",
            (1, 3),
            Some(("(1 +\n  (2 * 3)\n)", false)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 5),
            "%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (2, 2),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "50%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (1, 0),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "100%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (3, 0),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "25%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            None,
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "d50%",
            "  (2 * 3)\n)",
            (0, 2),
            Some(("f(a, [b, {c}], (d))\nx = (1 +", true)),
        ),
        (
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            "101%",
            "f(a, [b, {c}], (d))\nx = (1 +\n  (2 * 3)\n)",
            (0, 0),
            None,
        ),
        ("no brackets", (0, 0), "%", "no brackets", (0, 0), None),
        ("no brackets", (0, 0), "d%", "no brackets", (0, 0), None),
        ("a ) b", (0, 0), "%", "a ) b", (0, 0), None),
        ("a ) b", (0, 0), "d%", "a ) b", (0, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (2, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "2}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (6, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "3}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (10, 1), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "4}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "5}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "9}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), None),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "d}",
            "\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            Some(("a1\na2", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "y}",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            Some(("a1\na2", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "d2}",
            "\n\nc1\n  \nd1",
            (0, 0),
            Some(("a1\na2\n\nb1\nb2\nb3", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "c}x<Esc>",
            "x\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            Some(("a1\na2", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (0, 0),
            "d3}",
            "",
            (0, 0),
            Some(("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", true)),
        ),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), "d4}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (4, 1), "}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (6, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (4, 1), "{", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (2, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (4, 1), "2{", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (4, 1), "9{", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (4, 1), None),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (4, 1),
            "d}",
            "a1\na2\n\nb1\nb\n\n\nc1\n  \nd1",
            (4, 0),
            Some(("2\nb3", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (4, 1),
            "d{",
            "a1\na2\n2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (4, 1),
            "y{",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (4, 1),
            "c{x<Esc>",
            "a1\na2\nx2\nb3\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb", false)),
        ),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (10, 1), "{", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (7, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (10, 1), "}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (10, 1), None),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (10, 1),
            "d{",
            "a1\na2\n\nb1\nb2\nb3\n\n1",
            (7, 0),
            Some(("\nc1\n  \nd", false)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (10, 1),
            "d}",
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd",
            (10, 0),
            Some(("1", false)),
        ),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (10, 1), "3{", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (0, 0), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (6, 0), "}", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (10, 1), None),
        ("a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (6, 0), "{", "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1", (2, 0), None),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (6, 0),
            "d}",
            "a1\na2\n\nb1\nb2\nb3",
            (5, 0),
            Some(("\n\nc1\n  \nd1", true)),
        ),
        (
            "a1\na2\n\nb1\nb2\nb3\n\n\nc1\n  \nd1",
            (6, 0),
            "d{",
            "a1\na2\n\n\nc1\n  \nd1",
            (2, 0),
            Some(("\nb1\nb2\nb3", true)),
        ),
        ("x\n\n\ny", (1, 0), "}", "x\n\n\ny", (3, 0), None),
        ("x\n\n\ny", (1, 0), "{", "x\n\n\ny", (0, 0), None),
        ("x\n\n\ny", (1, 0), "d}", "x", (0, 0), Some(("\n\ny", true))),
        ("x\n\n\ny", (1, 0), "d{", "\n\ny", (0, 0), Some(("x", true))),
        ("one", (0, 1), "}", "one", (0, 2), None),
        ("one", (0, 1), "{", "one", (0, 0), None),
        ("one", (0, 1), "d}", "o", (0, 0), Some(("ne", false))),
        ("one", (0, 1), "d{", "ne", (0, 0), Some(("o", false))),
    ];
    check(CASES);
}
